#!/usr/bin/env bash
# scripts/hooks/post-install/vfio-bind-3090.sh
#
# Bind GPUs declared with role=vfio to vfio-pci at boot. Reads PCI IDs
# from the profile's hardware.gpu list (vendor:device IDs).
#
# Idempotent. Re-runnable if profile changes.

__SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__REPO_ROOT="$(cd "${__SCRIPT_DIR}/../../.." && pwd)"
# shellcheck source=../../build/lib/common.sh
. "${__REPO_ROOT}/scripts/build/lib/common.sh"
# shellcheck source=../../build/lib/observability.sh
. "${__REPO_ROOT}/scripts/build/lib/observability.sh"

STEP_ID="vfio-bind"

: "${SOVEREIGN_OS_PROFILE:=sain-01}"
load_profile "${SOVEREIGN_OS_PROFILE}"

log_step_header "${STEP_ID}" "bind VFIO GPUs at boot"

require_root

# Collect vfio PCI IDs from profile (concat device + vfio_companion)
vfio_ids="$(python3 -c "
import os, yaml
with open(os.environ['SOVEREIGN_OS_PROFILE_FILE']) as f:
    d = yaml.safe_load(f)
ids = []
for g in (d.get('hardware') or {}).get('gpu') or []:
    if g.get('role') == 'vfio':
        if g.get('pci_id') and '?' not in g['pci_id']:
            ids.append(g['pci_id'])
        if g.get('vfio_companion'):
            ids.append(g['vfio_companion'])
print(','.join(ids))
")"

if [ -z "${vfio_ids}" ]; then
  log_info "no VFIO GPUs declared in profile; nothing to bind"
  exit 0
fi

log_info "VFIO PCI IDs: ${vfio_ids}"

# ---- Configure GRUB cmdline ----
grub_cfg="/etc/default/grub"
if [ -f "${grub_cfg}" ]; then
  log_info "updating ${grub_cfg} with vfio-pci.ids=${vfio_ids}"
  if grep -q "^GRUB_CMDLINE_LINUX_DEFAULT=" "${grub_cfg}"; then
    # Replace existing vfio-pci.ids= or append
    if grep -q "vfio-pci.ids=" "${grub_cfg}"; then
      sed -i -E "s/vfio-pci\.ids=[^ \"]+/vfio-pci.ids=${vfio_ids}/" "${grub_cfg}"
    else
      sed -i -E "s/^(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*)\"/\1 vfio-pci.ids=${vfio_ids} amd_iommu=on iommu=pt\"/" "${grub_cfg}"
    fi
    # Trim duplicate spaces
    sed -i -E 's/  +/ /g' "${grub_cfg}"
  fi
  update-grub 2>&1 | sed 's/^/  /' || log_warn "update-grub not present; skipping (substrate-dependent)"
else
  log_warn "no /etc/default/grub; assuming systemd-boot (mkosi default)"
  # For systemd-boot: edit /boot/loader/entries/*.conf
  for entry in /boot/loader/entries/*.conf; do
    [ -e "${entry}" ] || continue
    if grep -q "vfio-pci.ids=" "${entry}"; then
      sed -i -E "s/vfio-pci\.ids=[^ ]+/vfio-pci.ids=${vfio_ids}/" "${entry}"
    else
      sed -i -E "/^options/ s/$/ vfio-pci.ids=${vfio_ids} amd_iommu=on iommu=pt/" "${entry}"
    fi
    log_info "  updated ${entry}"
  done
fi

# ---- Configure modprobe to load vfio-pci before other drivers ----
modprobe_dir="/etc/modprobe.d"
mkdir -p "${modprobe_dir}"
cat > "${modprobe_dir}/vfio.conf" <<EOF
# auto-generated by sovereign-os vfio-bind hook
options vfio-pci ids=${vfio_ids}
softdep nvidia pre: vfio-pci
softdep nouveau pre: vfio-pci
EOF
log_info "  wrote ${modprobe_dir}/vfio.conf"

# Update initramfs so vfio-pci loads early enough
if command -v update-initramfs >/dev/null 2>&1; then
  update-initramfs -u 2>&1 | sed 's/^/  /'
  # PIPESTATUS, not the trailing sed's status: `cmd | sed || warn` checks sed
  # (always 0), so the warning never fired on a real initramfs failure — and the
  # vfio binding would silently not apply at boot with no operator notice.
  [ "${PIPESTATUS[0]}" -eq 0 ] || log_warn "update-initramfs failed; manual rebuild may be needed (vfio binding will NOT apply at boot)"
fi

log_info "VFIO binding configured; reboot to apply"
emit_metric sovereign_os_post_install_vfio_bind_total 1 \
  "profile=\"${SOVEREIGN_OS_PROFILE}\",result=\"configured\""
log_info "${STEP_ID} complete"
