#!/usr/bin/env bash
# scripts/hooks/post-install/zfs-arc-clamp.sh
#
# Clamp the ZFS ARC (Adaptive Replacement Cache) to leave RAM
# available for the AI workloads. Default for sain-01: 128GB of the
# 256GB system memory.
#
# Master spec § 4.2 verbatim ("System Memory Partitioning"):
#   "ARC limit is explicitly clamped at exactly 128GB of the
#    system's 256GB overall space."
#   options zfs zfs_arc_max=137438953472
#
# 137438953472 = 128 * 1024^3 (operator-verbatim integer in §4.2).
# Cross-referenced by config/bootstrap/verify-grid.yaml check 03
# (R389 + R399 bidirectional consistency).

__SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__REPO_ROOT="$(cd "${__SCRIPT_DIR}/../../.." && pwd)"
# shellcheck source=../../build/lib/common.sh
. "${__REPO_ROOT}/scripts/build/lib/common.sh"
# shellcheck source=../../build/lib/observability.sh
. "${__REPO_ROOT}/scripts/build/lib/observability.sh"

STEP_ID="zfs-arc-clamp"

: "${SOVEREIGN_OS_PROFILE:=sain-01}"
load_profile "${SOVEREIGN_OS_PROFILE}"

: "${SOVEREIGN_OS_ARC_MAX_GB:=128}"

log_step_header "${STEP_ID}" "clamp ZFS ARC to ${SOVEREIGN_OS_ARC_MAX_GB}GB"

require_root

# Skip for non-ZFS layouts
layout="$(profile_field hardware.storage.layout)"
if [ "${layout}" != "zfs-tiered" ]; then
  log_info "profile storage layout is '${layout}'; skipping ARC clamp"
  exit 0
fi

# For sain-01 with 256GB target: clamp ARC at 128GB
# For old-workstation or smaller-memory profiles: scale to half the minimum
min_gb="$(profile_field hardware.memory.minimum_gb)"
target_gb="$(profile_field hardware.memory.target_gb)"
mem_gb="${target_gb:-${min_gb:-8}}"

# Use SOVEREIGN_OS_ARC_MAX_GB if set explicitly; otherwise scale to mem/2
if [ -z "${SOVEREIGN_OS_ARC_MAX_GB+x}" ] || [ "${SOVEREIGN_OS_ARC_MAX_GB}" = "128" ]; then
  if [ "${mem_gb}" -lt 64 ]; then
    SOVEREIGN_OS_ARC_MAX_GB=$((mem_gb / 2))
    log_info "auto-scaled ARC clamp to ${SOVEREIGN_OS_ARC_MAX_GB}GB (half of mem ${mem_gb}GB)"
  fi
fi

arc_max_bytes=$((SOVEREIGN_OS_ARC_MAX_GB * 1024 * 1024 * 1024))

# SDD-017 § "ZFS root layout": the operator may override the clamp
# byte-precisely (matching zfs_arc_max's native unit) via
# SOVEREIGN_OS_ZFS_ARC_MAX_BYTES. This is the override the SDD documents;
# it takes precedence over the SOVEREIGN_OS_ARC_MAX_GB convenience form.
# (Previously the SDD-named var was read by nothing — a silent no-op for
# any operator who followed the doc.)
if [ -n "${SOVEREIGN_OS_ZFS_ARC_MAX_BYTES:-}" ]; then
  arc_max_bytes="${SOVEREIGN_OS_ZFS_ARC_MAX_BYTES}"
  SOVEREIGN_OS_ARC_MAX_GB=$((arc_max_bytes / 1024 / 1024 / 1024))
  log_info "ARC clamp overridden via SOVEREIGN_OS_ZFS_ARC_MAX_BYTES=${arc_max_bytes} (~${SOVEREIGN_OS_ARC_MAX_GB}GB)"
fi

# Safety guard: in ZFS, zfs_arc_max=0 means UNLIMITED — writing it would do the
# EXACT OPPOSITE of this hook's job (clamp ARC so AI workloads keep their RAM)
# and silently let ARC consume all memory. A 0 can arise from a typo'd
# SOVEREIGN_OS_ZFS_ARC_MAX_BYTES=0 or an absurd auto-scale (mem<2GB → mem/2=0).
# ZFS also rejects a zfs_arc_max below its own 64 MiB floor. Refuse either
# rather than ship an un-clamping or rejected config.
if ! [[ "${arc_max_bytes}" =~ ^[0-9]+$ ]] || [ "${arc_max_bytes}" -lt 67108864 ]; then
  log_error "computed zfs_arc_max=${arc_max_bytes} is invalid: 0 means UNLIMITED ARC"
  log_error "  (un-clamping memory — the opposite of this hook) and any value below"
  log_error "  ZFS's 64 MiB floor is rejected. Refusing to write ${modprobe_file:-/etc/modprobe.d/zfs.conf}."
  log_error "  Check SOVEREIGN_OS_ARC_MAX_GB / SOVEREIGN_OS_ZFS_ARC_MAX_BYTES and the profile memory fields."
  emit_metric sovereign_os_post_install_arc_clamp_total 1 \
    "profile=\"${SOVEREIGN_OS_PROFILE}\",result=\"refused-invalid-arc-max\""
  exit 1
fi

# Persistent: /etc/modprobe.d/zfs.conf
modprobe_file="/etc/modprobe.d/zfs.conf"
log_info "writing ${modprobe_file} with zfs_arc_max=${arc_max_bytes} (${SOVEREIGN_OS_ARC_MAX_GB}GB)"
cat > "${modprobe_file}" <<EOF
# auto-generated by sovereign-os zfs-arc-clamp hook
# Clamp the ZFS Adaptive Replacement Cache to leave memory for AI workloads.
options zfs zfs_arc_max=${arc_max_bytes}
options zfs zfs_arc_min=$((arc_max_bytes / 4))
EOF

# Apply at runtime (if ZFS module already loaded)
runtime_file="/sys/module/zfs/parameters/zfs_arc_max"
if [ -w "${runtime_file}" ]; then
  echo "${arc_max_bytes}" > "${runtime_file}"
  log_info "runtime ARC max set to ${arc_max_bytes}"
fi

# Rebuild initramfs so the option applies at boot.
# R1 (SDD-998): serialized via boot_regen (concurrent first-boot initramfs rebuilds corrupt it).
if command -v update-initramfs >/dev/null 2>&1; then
  boot_regen update-initramfs -u 2>&1 | sed 's/^/  /' || log_warn "update-initramfs failed; manual run may be needed"
fi

emit_metric sovereign_os_post_install_arc_clamp_total 1 \
  "profile=\"${SOVEREIGN_OS_PROFILE}\",result=\"applied\""
emit_metric sovereign_os_post_install_arc_max_bytes "${arc_max_bytes:-0}" \
  "profile=\"${SOVEREIGN_OS_PROFILE}\""
log_info "${STEP_ID} complete"
