#!/usr/bin/env bash
# scripts/hooks/post-install/zfs-arc-clamp.sh
#
# Clamp the ZFS ARC (Adaptive Replacement Cache) to leave RAM
# available for the AI workloads. Default for sain-01: 128GB of the
# 256GB system memory.

__SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__REPO_ROOT="$(cd "${__SCRIPT_DIR}/../../.." && pwd)"
# shellcheck source=../../build/lib/common.sh
. "${__REPO_ROOT}/scripts/build/lib/common.sh"

STEP_ID="zfs-arc-clamp"

: "${SOVEREIGN_OS_PROFILE:=sain-01}"
load_profile "${SOVEREIGN_OS_PROFILE}"

: "${SOVEREIGN_OS_ARC_MAX_GB:=128}"

log_step_header "${STEP_ID}" "clamp ZFS ARC to ${SOVEREIGN_OS_ARC_MAX_GB}GB"

require_root

# Skip for non-ZFS layouts
layout="$(profile_field hardware.storage.layout)"
if [ "${layout}" != "zfs-tiered" ]; then
  log_info "profile storage layout is '${layout}'; skipping ARC clamp"
  exit 0
fi

# For sain-01 with 256GB target: clamp ARC at 128GB
# For old-workstation or smaller-memory profiles: scale to half the minimum
min_gb="$(profile_field hardware.memory.minimum_gb)"
target_gb="$(profile_field hardware.memory.target_gb)"
mem_gb="${target_gb:-${min_gb:-8}}"

# Use SOVEREIGN_OS_ARC_MAX_GB if set explicitly; otherwise scale to mem/2
if [ -z "${SOVEREIGN_OS_ARC_MAX_GB+x}" ] || [ "${SOVEREIGN_OS_ARC_MAX_GB}" = "128" ]; then
  if [ "${mem_gb}" -lt 64 ]; then
    SOVEREIGN_OS_ARC_MAX_GB=$((mem_gb / 2))
    log_info "auto-scaled ARC clamp to ${SOVEREIGN_OS_ARC_MAX_GB}GB (half of mem ${mem_gb}GB)"
  fi
fi

arc_max_bytes=$((SOVEREIGN_OS_ARC_MAX_GB * 1024 * 1024 * 1024))

# Persistent: /etc/modprobe.d/zfs.conf
modprobe_file="/etc/modprobe.d/zfs.conf"
log_info "writing ${modprobe_file} with zfs_arc_max=${arc_max_bytes} (${SOVEREIGN_OS_ARC_MAX_GB}GB)"
cat > "${modprobe_file}" <<EOF
# auto-generated by sovereign-os zfs-arc-clamp hook
# Clamp the ZFS Adaptive Replacement Cache to leave memory for AI workloads.
options zfs zfs_arc_max=${arc_max_bytes}
options zfs zfs_arc_min=$((arc_max_bytes / 4))
EOF

# Apply at runtime (if ZFS module already loaded)
runtime_file="/sys/module/zfs/parameters/zfs_arc_max"
if [ -w "${runtime_file}" ]; then
  echo "${arc_max_bytes}" > "${runtime_file}"
  log_info "runtime ARC max set to ${arc_max_bytes}"
fi

# Rebuild initramfs so the option applies at boot
if command -v update-initramfs >/dev/null 2>&1; then
  update-initramfs -u 2>&1 | sed 's/^/  /' || log_warn "update-initramfs failed; manual run may be needed"
fi

log_info "${STEP_ID} complete"
