#!/usr/bin/env bash
# tests/nspawn/test_models_docs.sh
#
# Layer 3 test for R206 — model-catalog doc renderer + freshness gate.
# Second consumer of the SDD-028 canonical-source pattern.

set -euo pipefail

__SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
__REPO_ROOT="$(cd "${__SCRIPT_DIR}/../.." && pwd)"

# python3 resolver — some CI envs lack PyYAML in the first python3.
PYTHON3="${PYTHON3:-python3}"
if ! "${PYTHON3}" -c "import yaml" >/dev/null 2>&1; then
  if /usr/bin/python3 -c "import yaml" >/dev/null 2>&1; then
    PYTHON3="/usr/bin/python3"
  fi
fi

fail=0
pass=0
ok() { echo "  PASS — $1"; pass=$((pass + 1)); }
ko() { echo "  FAIL — $1"; fail=$((fail + 1)); }

RENDER="${__REPO_ROOT}/scripts/models/render-catalog-md.py"
DOC="${__REPO_ROOT}/docs/src/model-catalog.md"
OSCTL="${__REPO_ROOT}/scripts/sovereign-osctl"
YAML="${__REPO_ROOT}/models/catalog.yaml"

echo "tests/nspawn/test_models_docs.sh"
echo

[ -x "${RENDER}" ] && ok "renderer executable" \
  || { ko "missing renderer"; exit 1; }
[ -f "${DOC}" ] && ok "doc present in-repo" \
  || { ko "doc not committed"; exit 1; }

set +e
"${PYTHON3}" "${RENDER}" --check >/dev/null 2>&1
rc=$?
set -e
[ "${rc}" -eq 0 ] && ok "--check rc=0 on fresh tree" \
  || ko "doc stale per --check (rc=${rc})"

grep -q "GENERATED by scripts/models/render-catalog-md.py" "${DOC}" \
  && ok "generated banner present" || ko "banner missing"
grep -q "SDD-028" "${DOC}" \
  && ok "doc cites SDD-028 pattern" || ko "no SDD-028 cross-ref"

# Tier sections must render
for tier in Pulse Logic Oracle; do
  grep -qE "^## ${tier} tier" "${DOC}" \
    && ok "${tier} tier section present" \
    || ko "${tier} tier missing"
done

# Catalog summary table
grep -qE "^\| pulse \|" "${DOC}" \
  && ok "summary table row 'pulse'" || ko "pulse row missing"
grep -qE "^\| oracle \|" "${DOC}" \
  && ok "summary table row 'oracle'" || ko "oracle row missing"

# Status badges
grep -q "✓ verified-real" "${DOC}" \
  && ok "verified-real badge present" || ko "no verified-real badge"
grep -q "◌ aspirational" "${DOC}" \
  && ok "aspirational badge present" || ko "no aspirational badge"

# Model count matches YAML
yaml_count=$(${PYTHON3} -c "import yaml; print(len(yaml.safe_load(open('${YAML}'))['catalog']['models']))")
doc_count=$(grep -cE "^### " "${DOC}")
[ "${doc_count}" -eq "${yaml_count}" ] \
  && ok "all ${yaml_count} models rendered (one ### header each)" \
  || ko "doc renders ${doc_count} headers, yaml has ${yaml_count} models"

# --stdout parity
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT
"${PYTHON3}" "${RENDER}" --stdout > "${WORK}/rendered.md"
diff -q "${DOC}" "${WORK}/rendered.md" >/dev/null \
  && ok "--stdout parity with on-disk doc" \
  || ko "--stdout drift"

# Drift detection
cp "${DOC}" "${WORK}/backup.md"
echo "STALE" >> "${DOC}"
set +e
"${PYTHON3}" "${RENDER}" --check >/dev/null 2>&1
rc=$?
set -e
cp "${WORK}/backup.md" "${DOC}"
[ "${rc}" -eq 1 ] && ok "--check detects stale doc (rc=1)" \
  || ko "stale not detected (rc=${rc})"

# osctl bridge
set +e
"${OSCTL}" models docs --stdout >/dev/null 2>&1
rc=$?
set -e
[ "${rc}" -eq 0 ] && ok "osctl models docs --stdout rc=0" \
  || ko "osctl bridge failed (rc=${rc})"

grep -q "models docs " "${OSCTL}" \
  && ok "osctl help documents 'models docs'" \
  || ko "osctl help missing 'models docs'"

echo
total=$((pass + fail))
echo "test_models_docs: ${pass}/${total} passed"
[ "${fail}" -eq 0 ] && { echo "PASS"; exit 0; } || { echo "FAIL"; exit 1; }
