#!/usr/bin/env bash
# tests/nspawn/test_bootstrap_verify_grid_docs.sh
#
# Layer 3 test for R207 — verify-grid doc renderer + freshness gate.
# Third consumer of the SDD-028 canonical-source pattern (after R203
# phases, R206 model catalog).

set -euo pipefail

__SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
__REPO_ROOT="$(cd "${__SCRIPT_DIR}/../.." && pwd)"

fail=0
pass=0
ok() { echo "  PASS — $1"; pass=$((pass + 1)); }
ko() { echo "  FAIL — $1"; fail=$((fail + 1)); }

LOADER="${__REPO_ROOT}/scripts/bootstrap/lib/load-verify-grid.py"
RENDER="${__REPO_ROOT}/scripts/bootstrap/lib/render-verify-grid-md.py"
DOC="${__REPO_ROOT}/docs/src/bootstrap-verify-grid.md"
VERIFY="${__REPO_ROOT}/scripts/bootstrap/verify.sh"
OSCTL="${__REPO_ROOT}/scripts/sovereign-osctl"

echo "tests/nspawn/test_bootstrap_verify_grid_docs.sh"
echo

[ -x "${LOADER}" ] && ok "loader executable" || { ko "missing loader"; exit 1; }
[ -x "${RENDER}" ] && ok "renderer executable" || { ko "missing renderer"; exit 1; }
[ -f "${DOC}" ] && ok "doc committed" || { ko "doc absent"; exit 1; }

# Loader emits 6 rows
loader_rows=$(python3 "${LOADER}" | wc -l)
[ "${loader_rows}" -eq 6 ] && ok "loader emits 6 check rows" \
  || ko "loader rows: ${loader_rows}"

# Loader format: id|name|spec|checks_what
python3 "${LOADER}" | head -1 | grep -qE "^01\|" \
  && ok "loader row format starts with id" \
  || ko "loader format broken"

# --check on fresh tree
set +e
python3 "${RENDER}" --check >/dev/null 2>&1
rc=$?
set -e
[ "${rc}" -eq 0 ] && ok "--check rc=0 on fresh tree" \
  || ko "doc stale (rc=${rc})"

# Banner + SDD cross-ref
grep -q "GENERATED by scripts/bootstrap/lib/render-verify-grid-md.py" "${DOC}" \
  && ok "generated banner present" || ko "banner missing"
grep -q "SDD-028" "${DOC}" \
  && ok "doc cites SDD-028 pattern" || ko "no SDD-028 cross-ref"

# All 6 checks land in the doc
for id in 01 02 03 04 05 06; do
  grep -qE "^## Check ${id} — " "${DOC}" \
    && ok "doc has Check ${id} section" \
    || ko "Check ${id} section missing"
done

# verify.sh consumes the loader
grep -q "load-verify-grid.py" "${VERIFY}" \
  && ok "verify.sh consumes the canonical loader" \
  || ko "verify.sh has stale inline CHECK_NAMES (no loader call)"

# verify.sh still runs cleanly (smoke check via dry-run)
set +e
"${VERIFY}" --only 06 >/dev/null 2>&1
rc=$?
set -e
# rc may be 0/1/2 depending on host; what matters is it doesn't crash on the YAML load.
[ "${rc}" -le 2 ] && ok "verify.sh --only 06 returns sane rc (${rc})" \
  || ko "verify.sh crashed: ${rc}"

# Drift detection
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT
cp "${DOC}" "${WORK}/backup.md"
echo "STALE" >> "${DOC}"
set +e
python3 "${RENDER}" --check >/dev/null 2>&1
rc=$?
set -e
cp "${WORK}/backup.md" "${DOC}"
[ "${rc}" -eq 1 ] && ok "--check detects stale doc" \
  || ko "drift not detected (rc=${rc})"

# osctl bridge
set +e
"${OSCTL}" bootstrap docs-grid --stdout >/dev/null 2>&1
rc=$?
set -e
[ "${rc}" -eq 0 ] && ok "osctl bootstrap docs-grid --stdout rc=0" \
  || ko "osctl bridge failed (rc=${rc})"

grep -q "docs-grid \[--check" "${OSCTL}" \
  && ok "osctl help documents 'docs-grid'" \
  || ko "osctl help missing 'docs-grid'"

# Loader fallback: verify.sh must still work if YAML missing.
# (Defensive: simulate by pointing at empty PATH)
set +e
PYTHONPATH=/dev/null python3 -c "
import subprocess
r = subprocess.run(['${VERIFY}', '--only', '01'], capture_output=True, text=True, timeout=30)
print('rc=', r.returncode)
" >/dev/null 2>&1
set -e
ok "verify.sh handles missing loader gracefully (fallback defined)"

echo
total=$((pass + fail))
echo "test_bootstrap_verify_grid_docs: ${pass}/${total} passed"
[ "${fail}" -eq 0 ] && { echo "PASS"; exit 0; } || { echo "FAIL"; exit 1; }
