#!/usr/bin/env bash
# tests/nspawn/test_bootstrap_docs.sh
#
# Layer 3 test for R203 — phase-doc renderer + freshness gate.

set -euo pipefail

__SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
__REPO_ROOT="$(cd "${__SCRIPT_DIR}/../.." && pwd)"

fail=0
pass=0
ok() { echo "  PASS — $1"; pass=$((pass + 1)); }
ko() { echo "  FAIL — $1"; fail=$((fail + 1)); }

RENDER="${__REPO_ROOT}/scripts/bootstrap/lib/render-phases-md.py"
DOC="${__REPO_ROOT}/docs/src/bootstrap-phases.md"
OSCTL="${__REPO_ROOT}/scripts/sovereign-osctl"

echo "tests/nspawn/test_bootstrap_docs.sh"
echo

[ -x "${RENDER}" ] && ok "renderer executable" \
  || { ko "missing renderer"; exit 1; }
[ -f "${DOC}" ] && ok "doc present in-repo" \
  || { ko "doc not committed"; exit 1; }

# --check on a fresh tree must pass
set +e
python3 "${RENDER}" --check >/dev/null 2>&1
rc=$?
set -e
[ "${rc}" -eq 0 ] && ok "--check rc=0 on fresh tree" \
  || ko "doc is stale per --check (expected 0, got ${rc})"

# Doc must carry the generated banner
grep -q "GENERATED by scripts/bootstrap/lib/render-phases-md.py" "${DOC}" \
  && ok "generated banner present" || ko "banner missing"

# All 5 phases must be sectioned in the doc
for ph in I II III IV V; do
  grep -qE "^## Phase ${ph} — " "${DOC}" \
    && ok "doc has Phase ${ph} section" || ko "Phase ${ph} section missing"
done

# Preconditions + postconditions land for every phase
preconds=$(grep -c "^\*\*Preconditions\*\*" "${DOC}")
postconds=$(grep -c "^\*\*Postconditions\*\*" "${DOC}")
[ "${preconds}" -eq 5 ] \
  && ok "5 Preconditions blocks rendered" \
  || ko "expected 5 Preconditions, got ${preconds}"
[ "${postconds}" -eq 5 ] \
  && ok "5 Postconditions blocks rendered" \
  || ko "expected 5 Postconditions, got ${postconds}"

# Phase table renders with the right counts
grep -qE "^\| I \| Minimal Trixie Base \| 3 \|" "${DOC}" \
  && ok "phase table row I correct" || ko "row I wrong"
grep -qE "^\| III \| Storage Layer \+ DKMS \(ZFS\) \| 7 \|" "${DOC}" \
  && ok "phase table row III correct" || ko "row III wrong"

# --stdout writes to stdout without touching the file
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT
python3 "${RENDER}" --stdout > "${WORK}/rendered.md" 2>&1
diff -q "${DOC}" "${WORK}/rendered.md" >/dev/null \
  && ok "--stdout output matches on-disk doc" \
  || ko "--stdout drift vs on-disk doc"

# Drift detection: temporarily corrupt the doc, --check must fail
cp "${DOC}" "${WORK}/backup.md"
echo "STALE-EDIT" >> "${DOC}"
set +e
python3 "${RENDER}" --check >/dev/null 2>&1
rc=$?
set -e
cp "${WORK}/backup.md" "${DOC}"
[ "${rc}" -eq 1 ] && ok "--check detects stale doc (rc=1)" \
  || ko "--check failed to detect drift (rc=${rc})"

# osctl bridge
set +e
"${OSCTL}" bootstrap docs --stdout >/dev/null 2>&1
rc=$?
set -e
[ "${rc}" -eq 0 ] && ok "osctl bootstrap docs --stdout rc=0" \
  || ko "osctl bridge failed (rc=${rc})"

# Help text wiring
grep -q "docs \[--check" "${OSCTL}" \
  && ok "osctl help documents 'docs' subverb" \
  || ko "osctl help missing 'docs' doc"

echo
total=$((pass + fail))
echo "test_bootstrap_docs: ${pass}/${total} passed"
[ "${fail}" -eq 0 ] && { echo "PASS"; exit 0; } || { echo "FAIL"; exit 1; }
