#!/usr/bin/env bash
# tests/nspawn/test_trinity_runtime_docs.sh
#
# Layer 3 test for R208 — trinity runtime-profile doc renderer.
# Fourth consumer of the SDD-028 canonical-source pattern.

set -euo pipefail

__SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
__REPO_ROOT="$(cd "${__SCRIPT_DIR}/../.." && pwd)"

fail=0
pass=0
ok() { echo "  PASS — $1"; pass=$((pass + 1)); }
ko() { echo "  FAIL — $1"; fail=$((fail + 1)); }

RENDER="${__REPO_ROOT}/scripts/trinity/render-runtime-profiles-md.py"
DOC="${__REPO_ROOT}/docs/src/trinity-runtime-profiles.md"
OSCTL="${__REPO_ROOT}/scripts/sovereign-osctl"

echo "tests/nspawn/test_trinity_runtime_docs.sh"
echo

[ -x "${RENDER}" ] && ok "renderer executable" \
  || { ko "missing renderer"; exit 1; }
[ -f "${DOC}" ] && ok "doc committed" \
  || { ko "doc absent"; exit 1; }

# --check on fresh tree
set +e
python3 "${RENDER}" --check >/dev/null 2>&1
rc=$?
set -e
[ "${rc}" -eq 0 ] && ok "--check rc=0 on fresh tree" \
  || ko "doc stale per --check (rc=${rc})"

grep -q "GENERATED by scripts/trinity/render-runtime-profiles-md.py" "${DOC}" \
  && ok "generated banner present" || ko "banner missing"
grep -q "SDD-028" "${DOC}" \
  && ok "doc cites SDD-028 pattern" || ko "no SDD-028 cross-ref"
grep -q "fourth application" "${DOC}" \
  && ok "doc records 4th SDD-028 application" \
  || ko "no application count in cross-refs"

# All 3 profiles render
for name in "Ultra-Sovereign Efficiency" "High-Concurrency Agent Burst" "Deep Context Synthesis"; do
  grep -qF "## ${name}" "${DOC}" \
    && ok "doc has section: ${name}" \
    || ko "missing section: ${name}"
done

# Summary table rows
for id in ultra-sovereign-efficiency high-concurrency-burst deep-context-synthesis; do
  grep -q "^| \`${id}\`" "${DOC}" \
    && ok "summary table row: ${id}" \
    || ko "missing summary row: ${id}"
done

# --stdout parity
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT
python3 "${RENDER}" --stdout > "${WORK}/rendered.md"
diff -q "${DOC}" "${WORK}/rendered.md" >/dev/null \
  && ok "--stdout parity" || ko "--stdout drift"

# Drift detection
cp "${DOC}" "${WORK}/backup.md"
echo "STALE" >> "${DOC}"
set +e
python3 "${RENDER}" --check >/dev/null 2>&1
rc=$?
set -e
cp "${WORK}/backup.md" "${DOC}"
[ "${rc}" -eq 1 ] && ok "--check detects stale doc" \
  || ko "stale not detected (rc=${rc})"

# osctl bridge
set +e
"${OSCTL}" trinity docs --stdout >/dev/null 2>&1
rc=$?
set -e
[ "${rc}" -eq 0 ] && ok "osctl trinity docs --stdout rc=0" \
  || ko "osctl bridge failed (rc=${rc})"

echo
total=$((pass + fail))
echo "test_trinity_runtime_docs: ${pass}/${total} passed"
[ "${fail}" -eq 0 ] && { echo "PASS"; exit 0; } || { echo "FAIL"; exit 1; }
