#!/usr/bin/env bash
# scripts/hooks/during-install/mok-enroll.sh
#
# Generate + enroll the operator's MOK (Machine Owner Key) for
# secure-boot. Only runs when profile.kernel.cmdline.secure_boot=signed.
# Operator confirms key generation; key location configurable.

__SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__REPO_ROOT="$(cd "${__SCRIPT_DIR}/../../.." && pwd)"
# shellcheck source=../../build/lib/common.sh
. "${__REPO_ROOT}/scripts/build/lib/common.sh"

STEP_ID="mok-enroll"

: "${SOVEREIGN_OS_PROFILE:=sain-01}"
load_profile "${SOVEREIGN_OS_PROFILE}"

: "${SOVEREIGN_OS_MOK_DIR:=/var/lib/sovereign-os/mok}"

log_step_header "${STEP_ID}" "MOK enrollment"

secure_boot="$(profile_field kernel.cmdline.secure_boot)"
if [ "${secure_boot}" != "signed" ]; then
  log_info "profile secure_boot=${secure_boot:-disabled}; MOK enrollment skipped"
  exit 0
fi

require_root
require_command openssl
require_command mokutil

mkdir -p "${SOVEREIGN_OS_MOK_DIR}"
chmod 700 "${SOVEREIGN_OS_MOK_DIR}"

key="${SOVEREIGN_OS_MOK_DIR}/MOK.priv"
crt="${SOVEREIGN_OS_MOK_DIR}/MOK.crt"
der="${SOVEREIGN_OS_MOK_DIR}/MOK.der"

if [ -f "${key}" ] && [ -f "${der}" ]; then
  log_info "MOK already present at ${SOVEREIGN_OS_MOK_DIR}; reusing"
else
  log_info "generating MOK key pair at ${SOVEREIGN_OS_MOK_DIR}"
  openssl req -new -x509 -newkey rsa:2048 -keyout "${key}" -outform DER \
    -out "${der}" -nodes -days 36500 \
    -subj "/CN=sovereign-os MOK/" 2>&1 | sed 's/^/  /'
  openssl x509 -in "${der}" -inform DER -outform PEM -out "${crt}" 2>&1 | sed 's/^/  /'
  chmod 600 "${key}"
  chmod 644 "${der}" "${crt}"
fi

# Queue for MOK manager enrollment (operator confirms at next reboot)
if mokutil --test-key "${der}" 2>&1 | grep -q 'is already enrolled'; then
  log_info "MOK already enrolled"
else
  log_info "queueing MOK for enrollment via mokutil --import"
  log_warn "  At next reboot, MOK Manager will prompt to enroll the key."
  log_warn "  Have the password ready (you'll set it now)."
  mokutil --import "${der}" || {
    log_error "mokutil --import failed"
    exit 1
  }
fi

# Export key paths for the build pipeline's image-sign step
env_file="/etc/sovereign-os/mok-paths.sh"
mkdir -p "$(dirname "${env_file}")"
cat > "${env_file}" <<EOF
# auto-generated by ${STEP_ID}
export SOVEREIGN_OS_MOK_KEY="${key}"
export SOVEREIGN_OS_MOK_CERT="${der}"
EOF
log_info "MOK paths written: ${env_file}"

log_info "${STEP_ID} complete (reboot required to finalize MOK enrollment)"
