#!/usr/bin/env python3
"""scripts/models/render-catalog-md.py — R212 model-catalog doc renderer.

Implements the SDD-028 canonical-source pattern for the model catalog:
reads models/catalog.yaml + emits docs/src/model-catalog.md as an
operator-readable rundown of the catalog.

R212 expansion: the doc now surfaces the model-class taxonomy
(class / quantization / size_class / purpose / vram_gib_min /
context_window_tokens / base_model) so operators can find the right
model for their job at a glance.

Drift between the catalog YAML and the operator doc is structurally
impossible — the doc is regenerated on every invocation, and
`--check` mode fails CI if the on-disk doc is stale.

Usage:
  render-catalog-md.py                  write the doc + return 0
  render-catalog-md.py --check          rc=1 if stale (CI gate)
  render-catalog-md.py --stdout         write to stdout
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
YAML_PATH = REPO_ROOT / "models" / "catalog.yaml"
DOC_PATH = REPO_ROOT / "docs" / "src" / "model-catalog.md"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/models/render-catalog-md.py from "
    "models/catalog.yaml. Do NOT edit this file directly — edit the "
    "YAML and re-run the renderer. R212 (SDD-028 pattern; extended from R206). -->\n"
)

STATUS_BADGE = {
    "verified-real": "✓ verified-real",
    "aspirational": "◌ aspirational",
    "operator-must-confirm": "? operator-must-confirm",
}

# R212 — operator-facing display labels for class.
CLASS_LABEL = {
    "llm": "LLM (general)",
    "slm": "SLM (small)",
    "rlm": "RLM (reasoning)",
    "ternary-lm": "Ternary LM (1.58-bit)",
    "lora-adapter": "LoRA adapter",
    "embed": "Embedding",
    "vision": "Vision",
    "multimodal": "Multimodal",
    "code": "Code-specialised",
    "mixture": "Mixture-of-Experts",
    "speculative": "Speculative draft",
    "reranker": "Reranker (cross-encoder)",
}


def render(doc: dict) -> str:
    catalog = doc["catalog"]
    models = catalog["models"]
    lines = [GENERATED_BANNER]
    lines.append("# Model catalog — Genesis Trinity (master spec § 17)\n")
    lines.append(
        f"Canonical declaration of the {len(models)} models this system "
        "intends to host across Pulse / Logic / Oracle / Router tiers, "
        "spanning the full R212 taxonomy (class × quantization × "
        "size_class × purpose).\n"
    )
    lines.append(
        "This doc is regenerated from `models/catalog.yaml` on every "
        "invocation of `scripts/models/render-catalog-md.py`. The same "
        "YAML drives `scripts/models/pull.sh` (operator-driven pull) and "
        "`scripts/models/verify.sh` (resident integrity check), so the "
        "doc, the puller, and the verifier can never drift.\n"
    )

    # Aggregate by tier
    by_tier: dict[str, list[dict]] = {}
    for m in models:
        by_tier.setdefault(m["tier"], []).append(m)

    # --- summary tables ---
    lines.append("## Catalog summary by tier\n")
    lines.append("| Tier | Count | Verified-real | Aspirational |")
    lines.append("|------|-------|---------------|--------------|")
    for tier in ("pulse", "logic", "oracle", "router"):
        entries = by_tier.get(tier, [])
        verified = sum(1 for m in entries if m["status"] == "verified-real")
        aspirational = sum(1 for m in entries if m["status"] == "aspirational")
        lines.append(
            f"| {tier} | {len(entries)} | {verified} | {aspirational} |"
        )
    lines.append("")

    # Class breakdown (R212)
    class_counts = Counter(m.get("class", "(unspecified)") for m in models)
    lines.append("## Catalog by class (R212 taxonomy)\n")
    lines.append("| Class | Count |")
    lines.append("|-------|-------|")
    for cls in sorted(class_counts):
        label = CLASS_LABEL.get(cls, cls)
        lines.append(f"| `{cls}` — {label} | {class_counts[cls]} |")
    lines.append("")

    # Purpose breakdown
    purpose_counts: Counter = Counter()
    for m in models:
        for p in m.get("purpose", []) or []:
            purpose_counts[p] += 1
    if purpose_counts:
        lines.append("## Catalog by purpose (R212 taxonomy)\n")
        lines.append("| Purpose | Count |")
        lines.append("|---------|-------|")
        for p in sorted(purpose_counts):
            lines.append(f"| `{p}` | {purpose_counts[p]} |")
        lines.append("")

    # --- per-tier model detail ---
    for tier in ("pulse", "logic", "oracle", "router"):
        entries = by_tier.get(tier, [])
        if not entries:
            continue
        lines.append(f"## {tier.capitalize()} tier (master spec § 17)\n")
        for m in entries:
            lines.append(f"### {m['id']}\n")
            lines.append(f"- **Status:** {STATUS_BADGE.get(m['status'], m['status'])}")
            cls = m.get("class")
            if cls:
                lines.append(f"- **Class:** `{cls}` — {CLASS_LABEL.get(cls, cls)}")
            if m.get("quantization"):
                lines.append(f"- **Quantization:** `{m['quantization']}`")
            if m.get("size_class"):
                lines.append(f"- **Size class:** `{m['size_class']}`")
            purposes = m.get("purpose") or []
            if purposes:
                lines.append(
                    f"- **Purpose:** {', '.join(f'`{p}`' for p in purposes)}"
                )
            lines.append(f"- **Engine:** `{m['engine']}`")
            lines.append(f"- **License:** {m['license']}")
            if m["status"] == "verified-real" and m.get("hf_repo_id"):
                lines.append(f"- **HF repo id:** `{m['hf_repo_id']}`")
            if m.get("base_model"):
                lines.append(f"- **Base model (LoRA):** `{m['base_model']}`")
            if m.get("parameters_millions") is not None:
                lines.append(f"- **Parameters:** {m['parameters_millions']:.1f} M")
            if m.get("vram_gib_min") is not None:
                lines.append(f"- **VRAM minimum (GiB):** {m['vram_gib_min']}")
            if m.get("context_window_tokens") is not None:
                lines.append(
                    f"- **Context window (tokens):** {m['context_window_tokens']:,}"
                )
            if m.get("master_spec_section"):
                lines.append(f"- **Master spec:** {m['master_spec_section']}")
            bindings = m.get("runtime_profile_bindings") or []
            if bindings:
                lines.append(f"- **Runtime profiles:** {', '.join(bindings)}")
            if m["status"] == "aspirational" and m.get("closest_real_alternative"):
                lines.append(
                    f"- **Closest real alternative:** `{m['closest_real_alternative']}`"
                )
            note = m.get("operator_note", "").strip()
            if note:
                lines.append("")
                lines.append("**Operator note:**")
                lines.append("")
                for ln in note.splitlines():
                    lines.append(f"> {ln}".rstrip())
            lines.append("")

    lines.append("## Cross-references\n")
    lines.append("- `models/catalog.yaml` — canonical source")
    lines.append("- `schemas/model-catalog.schema.yaml` — JSON Schema (1.1.0 at R212)")
    lines.append("- `scripts/models/pull.sh` — operator-driven HF pull")
    lines.append("- `scripts/models/verify.sh` — resident integrity verifier")
    lines.append("- `sovereign-osctl models {list,pull,verify,size,remove,docs}` — operator surface")
    lines.append("- SDD-011 — inference backend stack decision")
    lines.append("- SDD-028 — canonical-YAML source pattern this doc follows")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()

    if not YAML_PATH.exists():
        print(f"ERROR catalog.yaml not found at {YAML_PATH}", file=sys.stderr)
        return 2

    with YAML_PATH.open() as fh:
        doc = yaml.safe_load(fh)

    rendered = render(doc)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        if not DOC_PATH.exists():
            print(f"ERROR doc not present at {DOC_PATH}", file=sys.stderr)
            return 1
        if DOC_PATH.read_text() != rendered:
            print(
                "ERROR docs/src/model-catalog.md is stale; "
                "rerun render-catalog-md.py to refresh.",
                file=sys.stderr,
            )
            return 1
        print("docs/src/model-catalog.md is fresh")
        return 0

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(rendered)
    print(f"wrote {DOC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
