#!/usr/bin/env python3
"""scripts/models/render-catalog-md.py — R206 model-catalog doc renderer.

Implements the SDD-028 canonical-source pattern for the model catalog:
reads models/catalog.yaml + emits docs/src/model-catalog.md as an
operator-readable rundown of the 8-entry Genesis Trinity catalog.

Drift between the catalog YAML and the operator doc is structurally
impossible — the doc is regenerated on every invocation, and
`--check` mode fails CI if the on-disk doc is stale.

Usage:
  render-catalog-md.py                  write the doc + return 0
  render-catalog-md.py --check          rc=1 if stale (CI gate)
  render-catalog-md.py --stdout         write to stdout
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
YAML_PATH = REPO_ROOT / "models" / "catalog.yaml"
DOC_PATH = REPO_ROOT / "docs" / "src" / "model-catalog.md"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/models/render-catalog-md.py from "
    "models/catalog.yaml. Do NOT edit this file directly — edit the "
    "YAML and re-run the renderer. R206 (SDD-028 pattern). -->\n"
)

STATUS_BADGE = {
    "verified-real": "✓ verified-real",
    "aspirational": "◌ aspirational",
    "operator-must-confirm": "? operator-must-confirm",
}


def render(doc: dict) -> str:
    catalog = doc["catalog"]
    models = catalog["models"]
    lines = [GENERATED_BANNER]
    lines.append("# Model catalog — Genesis Trinity (master spec § 17)\n")
    lines.append(
        f"Canonical declaration of the {len(models)} models this system "
        "intends to host across Pulse / Logic / Oracle tiers.\n"
    )
    lines.append(
        "This doc is regenerated from `models/catalog.yaml` on every "
        "invocation of `scripts/models/render-catalog-md.py`. The same "
        "YAML drives `scripts/models/pull.sh` (operator-driven pull) and "
        "`scripts/models/verify.sh` (resident integrity check), so the "
        "doc, the puller, and the verifier can never drift.\n"
    )

    # Aggregate by tier
    by_tier: dict[str, list[dict]] = {}
    for m in models:
        by_tier.setdefault(m["tier"], []).append(m)

    lines.append("## Catalog summary\n")
    lines.append("| Tier | Count | Verified-real | Aspirational |")
    lines.append("|------|-------|---------------|--------------|")
    for tier in ("pulse", "logic", "oracle"):
        entries = by_tier.get(tier, [])
        verified = sum(1 for m in entries if m["status"] == "verified-real")
        aspirational = sum(1 for m in entries if m["status"] == "aspirational")
        lines.append(f"| {tier} | {len(entries)} | {verified} | {aspirational} |")
    lines.append("")

    for tier in ("pulse", "logic", "oracle"):
        entries = by_tier.get(tier, [])
        if not entries:
            continue
        lines.append(f"## {tier.capitalize()} tier (master spec § 17)\n")
        for m in entries:
            lines.append(f"### {m['id']}\n")
            lines.append(f"- **Status:** {STATUS_BADGE.get(m['status'], m['status'])}")
            lines.append(f"- **Engine:** `{m['engine']}`")
            lines.append(f"- **License:** {m['license']}")
            if m["status"] == "verified-real" and m.get("hf_repo_id"):
                lines.append(f"- **HF repo id:** `{m['hf_repo_id']}`")
            if m.get("parameters_millions") is not None:
                lines.append(f"- **Parameters:** {m['parameters_millions']:.1f} M")
            if m.get("master_spec_section"):
                lines.append(f"- **Master spec:** {m['master_spec_section']}")
            bindings = m.get("runtime_profile_bindings") or []
            if bindings:
                lines.append(f"- **Runtime profiles:** {', '.join(bindings)}")
            if m["status"] == "aspirational" and m.get("closest_real_alternative"):
                lines.append(
                    f"- **Closest real alternative:** `{m['closest_real_alternative']}`"
                )
            note = m.get("operator_note", "").strip()
            if note:
                lines.append("")
                lines.append("**Operator note:**")
                lines.append("")
                for ln in note.splitlines():
                    lines.append(f"> {ln}".rstrip())
            lines.append("")

    lines.append("## Cross-references\n")
    lines.append("- `models/catalog.yaml` — canonical source")
    lines.append("- `schemas/model-catalog.schema.yaml` — JSON Schema for the YAML")
    lines.append("- `scripts/models/pull.sh` — operator-driven HF pull")
    lines.append("- `scripts/models/verify.sh` — resident integrity verifier")
    lines.append("- `sovereign-osctl models {list,pull,verify,size,remove}` — operator surface")
    lines.append("- SDD-011 — inference backend stack decision")
    lines.append("- SDD-028 — canonical-YAML source pattern that drives this doc")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()

    if not YAML_PATH.exists():
        print(f"ERROR catalog.yaml not found at {YAML_PATH}", file=sys.stderr)
        return 2

    with YAML_PATH.open() as fh:
        doc = yaml.safe_load(fh)

    rendered = render(doc)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        if not DOC_PATH.exists():
            print(f"ERROR doc not present at {DOC_PATH}", file=sys.stderr)
            return 1
        if DOC_PATH.read_text() != rendered:
            print(
                "ERROR docs/src/model-catalog.md is stale; "
                "rerun render-catalog-md.py to refresh.",
                file=sys.stderr,
            )
            return 1
        print("docs/src/model-catalog.md is fresh")
        return 0

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(rendered)
    print(f"wrote {DOC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
