#!/usr/bin/env python3
"""Generate backlog/SHIPPED-ROLLUP.md — the per-milestone delivery roll-up (F-2026-038).

The backlog catalogues 14,080 R-rows across 84 milestone files, but "how done is M0xx"
was only answerable by reading SHIPPED.md, which self-describes as a SAMPLED snapshot
with a "state TBD" section. This generator makes it queryable.

Honest metric choice: SHIPPED.md records delivered SURFACES (a single R-row typically
ships as several — an alert + a dashboard + an API + a doc + tests), so a literal
"shipped-rows / R-rows" ratio exceeds 100% and misleads. Instead this reports, per
milestone:

  * catalogued R-rows  — distinct R##### ids in backlog/milestones/M*.md (clean denominator);
  * delivered?         — whether SHIPPED.md carries a `## M###` production-delivery section;
  * shipped surfaces   — data rows recorded in that section (a delivery-DEPTH signal, NOT a
                         completion %, because rows are surfaces not R-rows).

and a grand roll-up: how many of the N milestones have production delivery recorded.

Run `python3 scripts/backlog/gen-shipped-rollup.py` after backlog/SHIPPED.md or a
milestone file changes; `--check` exits non-zero if the committed roll-up is stale.
tests/lint/test_shipped_rollup.py enforces it in CI.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MILESTONES = REPO_ROOT / "backlog" / "milestones"
SHIPPED = REPO_ROOT / "backlog" / "SHIPPED.md"
OUT = REPO_ROOT / "backlog" / "SHIPPED-ROLLUP.md"

_MILESTONE_ID_RE = re.compile(r"^(M\d+)")
_RROW_RE = re.compile(r"\bR\d{5}\b")
_SHIPPED_SECTION_RE = re.compile(r"^##\s+(M\d+)(?:\s|\+|—|-)")
_SEP_ROW_RE = re.compile(r"^\|[\s:|-]+\|?\s*$")


def _milestone_files() -> list[Path]:
    return sorted(p for p in MILESTONES.glob("M*.md") if p.name != "INDEX.md")


def _catalogued_rrows(path: Path) -> int:
    return len(set(_RROW_RE.findall(path.read_text(encoding="utf-8"))))


def _shipped_sections() -> dict[str, int]:
    """milestone-id -> count of shipped-surface DATA rows recorded in SHIPPED.md.

    A `## M###` section can cover several milestones (`## M045 + M013 — …`); each id in
    the header gets credited with the section's data-row count. Data rows = pipe-rows in
    the section minus table separators minus one header per table (== separator count).
    """
    out: dict[str, int] = {}
    if not SHIPPED.is_file():
        return out
    current: list[str] = []
    pipe_rows = 0
    sep_rows = 0

    def _flush() -> None:
        data_rows = max(0, pipe_rows - 2 * sep_rows)  # 1 header + 1 sep per table
        for mid in current:
            out[mid] = out.get(mid, 0) + data_rows

    for line in SHIPPED.read_text(encoding="utf-8").splitlines():
        m = _SHIPPED_SECTION_RE.match(line)
        if m:
            _flush()
            # a header may name several milestones: "## M045 + M013 — …"
            current = re.findall(r"\bM\d+\b", line.split("—")[0])
            pipe_rows = sep_rows = 0
            continue
        if current and line.startswith("|"):
            if _SEP_ROW_RE.match(line):
                sep_rows += 1
            else:
                pipe_rows += 1
    _flush()
    return out


def _rows() -> list[tuple[str, int, bool, int]]:
    shipped = _shipped_sections()
    rows: list[tuple[str, int, bool, int]] = []
    for f in _milestone_files():
        m = _MILESTONE_ID_RE.match(f.name)
        if not m:
            continue
        mid = m.group(1)
        catalogued = _catalogued_rrows(f)
        surfaces = shipped.get(mid, 0)
        rows.append((mid, catalogued, mid in shipped, surfaces))
    return rows


def _global_distinct_rrows() -> int:
    """Distinct R##### across ALL milestone files — the authoritative catalogue total.
    (Summing per-milestone counts would double-count the handful of cross-referenced
    R-rows that appear in more than one milestone file.)"""
    seen: set[str] = set()
    for f in _milestone_files():
        seen.update(_RROW_RE.findall(f.read_text(encoding="utf-8")))
    return len(seen)


def render() -> str:
    rows = _rows()
    total_ms = len(rows)
    delivered = sum(1 for _, _, d, _ in rows if d)
    total_rrows = _global_distinct_rrows()
    total_surfaces = sum(s for _, _, _, s in rows)
    pct = (delivered * 100 // total_ms) if total_ms else 0

    lines = [
        "# Backlog delivery roll-up (generated — do not edit)",
        "",
        "> Generated by `scripts/backlog/gen-shipped-rollup.py` from `backlog/milestones/M*.md`",
        "> (catalogued R-rows) + `backlog/SHIPPED.md` (production-delivery records). Regenerate",
        "> after either changes; `tests/lint/test_shipped_rollup.py` fails CI on drift.",
        ">",
        "> **Reading it:** *catalogued R-rows* is the milestone's requirement count. *delivered*",
        "> means SHIPPED.md carries a production-delivery section for it. *shipped surfaces* counts",
        "> the delivered surfaces recorded there — a delivery-DEPTH signal, **not** a completion %",
        "> (one R-row typically ships as several surfaces, so surfaces/R-rows is not a ratio).",
        "",
        "## Grand roll-up",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Milestones | {total_ms} |",
        f"| Milestones with production delivery recorded | {delivered} ({pct}%) |",
        f"| Milestones catalogued-only (no delivery record yet) | {total_ms - delivered} |",
        f"| Catalogued R-rows (distinct, all milestones) | {total_rrows} |",
        f"| Shipped surfaces recorded (total) | {total_surfaces} |",
        "",
        "## Per milestone",
        "",
        "| Milestone | Catalogued R-rows | Delivered? | Shipped surfaces |",
        "|---|---:|:--:|---:|",
    ]
    for mid, catalogued, is_delivered, surfaces in sorted(rows, key=lambda r: r[0]):
        mark = "✓" if is_delivered else "—"
        lines.append(f"| {mid} | {catalogued} | {mark} | {surfaces if is_delivered else ''} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != content:
            print(f"DRIFT: {OUT.relative_to(REPO_ROOT)} is stale — run "
                  "`python3 scripts/backlog/gen-shipped-rollup.py`", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(REPO_ROOT)} is up to date")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
