#!/usr/bin/env python3
"""Generate backlog/INDEX.md — the milestone catalog index.

The old INDEX.md claimed to be auto-generated but had NO generator and no CI
lock — so it drifted: header said "82 milestones · 14080 R-rows" while the
tree carried 84 files / 14,079 distinct R-rows, M085/M086 were missing from
the table, and ~14 per-milestone counts were wrong (found 2026-07-17). This
generator + tests/lint/test_backlog_index.py make the claim true, the same
arrangement as gen-shipped-rollup.py / SHIPPED-ROLLUP.md (F-2026-038).

Metric: distinct R##### ids per milestone file — the SAME metric
SHIPPED-ROLLUP.md uses, so the two generated catalogs always agree on
totals. (The old INDEX counted literal `| R##### |` table rows, which
undercounted milestones that carry R-rows outside the main table.)

Run `python3 scripts/backlog/gen-index.py` after a milestone file changes;
`--check` exits non-zero if the committed INDEX is stale.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MILESTONES = REPO_ROOT / "backlog" / "milestones"
OUT = REPO_ROOT / "backlog" / "INDEX.md"

_RROW_RE = re.compile(r"\bR\d{5}\b")


def _milestone_files() -> list[Path]:
    return sorted(p for p in MILESTONES.glob("M*.md") if p.name != "INDEX.md")


def _catalogued_rrows(path: Path) -> int:
    return len(set(_RROW_RE.findall(path.read_text(encoding="utf-8"))))


def _global_distinct_rrows(files: list[Path]) -> int:
    """Distinct R##### across ALL milestone files — same headline metric as
    gen-shipped-rollup.py (a per-file sum double-counts the ~98 R-ids that
    appear in more than one milestone file)."""
    seen: set[str] = set()
    for f in files:
        seen.update(_RROW_RE.findall(f.read_text(encoding="utf-8")))
    return len(seen)


def _title(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def render() -> str:
    files = _milestone_files()
    total_rrows = _global_distinct_rrows(files)

    lines: list[str] = []
    lines.append("# sovereign-os · backlog/INDEX.md")
    lines.append("")
    lines.append(
        "> **Auto-generated by `scripts/backlog/gen-index.py`** (CI-locked by "
        "`tests/lint/test_backlog_index.py`) — factual index of "
        "`backlog/milestones/M*.md`. No invention; each row is a real milestone "
        "file + its distinct-R-row count (same metric as SHIPPED-ROLLUP.md, so "
        "the two catalogs always agree on totals). Regenerate after a milestone "
        "change: `python3 scripts/backlog/gen-index.py`."
    )
    lines.append("")
    lines.append(
        f"**Catalog totals:** {len(files)} milestone files · **{total_rrows:,} "
        f"distinct R-rows** (global-distinct across all milestone files — a "
        f"per-file sum runs higher because some R-ids appear in several "
        f"milestones) · combines with selfdef's 11,520 R-rows for the "
        f"cross-repo \"~10,000+ requirements\" operator mandate."
    )
    lines.append("")
    lines.append("| Milestone | R-rows | Title |")
    lines.append("|---|---:|---|")
    for f in files:
        lines.append(
            f"| [{f.stem}](milestones/{f.name}) | {_catalogued_rrows(f)} | {_title(f)} |"
        )
    lines.append("")
    lines.append(
        "**Pre-existing parent rollups (per-milestone counts inherit selfdef's "
        "240-R-row pattern; sovereign-os carries its own ranges):**"
    )
    lines.append("- Epics: E0NNN catalog spans selfdef + sovereign-os.")
    lines.append("- Modules: M00NNN catalog spans both repos.")
    lines.append("- Features: F0NNNN catalog spans both repos.")
    lines.append("")
    lines.append(
        "The combined selfdef + sovereign-os catalog satisfies the operator's "
        "\"10,000+ requirements / 400+ epics / 1000+ modules / 5000+ features\" "
        "foundational mandate per `context.md`. See selfdef `backlog/INDEX.md` "
        "for that side. Delivery state per milestone: `backlog/SHIPPED-ROLLUP.md` "
        "(generated) + `backlog/SHIPPED.md` (records)."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if OUT.read_text(encoding="utf-8") != content:
            print(f"STALE: {OUT.relative_to(REPO_ROOT)} — regenerate with "
                  f"python3 scripts/backlog/gen-index.py", file=sys.stderr)
            return 1
        print(f"OK: {OUT.relative_to(REPO_ROOT)} is current")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
