#!/usr/bin/env python3
"""scripts/bootstrap/lib/render-phases-md.py — R203 phase-doc renderer.

Reads config/bootstrap/phases.yaml and emits docs/src/bootstrap-phases.md
as an operator-readable rundown of the master spec § 12 5-phase pipeline,
including preconditions + postconditions per phase.

Generated. Drift between this doc and the YAML is structurally
impossible because the doc is regenerated from the YAML on every
invocation.

Usage:
  render-phases-md.py                  write the doc + return 0
  render-phases-md.py --check          compare against the on-disk doc;
                                       exit 1 if stale (CI gate)
  render-phases-md.py --stdout         write to stdout instead of file
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
YAML_PATH = REPO_ROOT / "config" / "bootstrap" / "phases.yaml"
DOC_PATH = REPO_ROOT / "docs" / "src" / "bootstrap-phases.md"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/bootstrap/lib/render-phases-md.py from "
    "config/bootstrap/phases.yaml. Do NOT edit this file directly — "
    "edit the YAML and re-run the renderer. R203. -->\n"
)


def kind_of(path: str) -> str:
    if path.startswith("scripts/build/") and path.endswith(".sh"):
        return "build-step"
    if path.startswith("scripts/hooks/during-install/"):
        return "installer-hook"
    if path.startswith("scripts/hooks/post-install/"):
        return "post-install-hook"
    if path.startswith("scripts/hooks/recurrent/"):
        return "recurrent-hook"
    if path.startswith("systemd/system/") and path.endswith(".service"):
        return "systemd-unit"
    if path.startswith("systemd/system/") and path.endswith(".timer"):
        return "systemd-timer"
    if path.startswith("config/") or path.startswith("profiles/") or path.startswith("whitelabel/"):
        return "config"
    if path.startswith("scripts/") and (path.endswith(".py") or path.endswith(".sh")):
        return "tooling"
    return "other"


def render(doc: dict) -> str:
    lines = [GENERATED_BANNER]
    lines.append("# Master spec § 12 — 5-phase bootstrap pipeline\n")
    lines.append(
        "Operators MUST honor the chronological order. Per master spec § 12: "
        "*\"Each phase must be completed and validated before the downstream phase "
        "is initiated.\"*\n"
    )
    lines.append(
        "This doc is regenerated from `config/bootstrap/phases.yaml` on every "
        "invocation of `scripts/bootstrap/lib/render-phases-md.py`. The same "
        "YAML drives `sovereign-osctl bootstrap phases` (inventory) and "
        "`sovereign-osctl bootstrap run` (dry-run plan), so the doc, the "
        "inventory, and the executor can never drift.\n"
    )
    lines.append("## Phase table\n")
    lines.append("| Phase | Name | Artifacts |")
    lines.append("|-------|------|-----------|")
    for p in doc["phases"]:
        lines.append(f"| {p['id']} | {p['name']} | {len(p['artifacts'])} |")
    lines.append("")

    for p in doc["phases"]:
        lines.append(f"## Phase {p['id']} — {p['name']}\n")
        lines.append(f"**Description.** {p['description']}\n")

        pre = p.get("preconditions", [])
        if pre:
            lines.append("**Preconditions** (must hold BEFORE this phase runs):\n")
            for item in pre:
                lines.append(f"- {item}")
            lines.append("")

        post = p.get("postconditions", [])
        if post:
            lines.append("**Postconditions** (state AFTER this phase completes):\n")
            for item in post:
                lines.append(f"- {item}")
            lines.append("")

        lines.append("**Artifacts:**\n")
        for art in p["artifacts"]:
            lines.append(f"- `{art}` *({kind_of(art)})*")
        lines.append("")

    lines.append("## Cross-references\n")
    lines.append(
        "- `sovereign-osctl bootstrap phases` — inventory (artifact-presence check)"
    )
    lines.append(
        "- `sovereign-osctl bootstrap run --phase N` — dry-run execution plan"
    )
    lines.append(
        "- `sovereign-osctl bootstrap verify` — master spec § 22 6-check operational grid (LIVE node)"
    )
    lines.append(
        "- `config/bootstrap/phases.yaml` — canonical source consumed by every surface above"
    )
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare against on-disk doc; rc=1 if stale")
    ap.add_argument("--stdout", action="store_true",
                    help="write to stdout instead of the doc file")
    args = ap.parse_args()

    if not YAML_PATH.exists():
        print(f"ERROR phases.yaml not found at {YAML_PATH}", file=sys.stderr)
        return 2

    with YAML_PATH.open() as fh:
        doc = yaml.safe_load(fh)

    rendered = render(doc)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        if not DOC_PATH.exists():
            print(f"ERROR doc not present at {DOC_PATH}", file=sys.stderr)
            return 1
        on_disk = DOC_PATH.read_text()
        if on_disk != rendered:
            print(
                "ERROR docs/src/bootstrap-phases.md is stale; "
                "rerun render-phases-md.py to refresh.",
                file=sys.stderr,
            )
            return 1
        print("docs/src/bootstrap-phases.md is fresh")
        return 0

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(rendered)
    print(f"wrote {DOC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
