#!/usr/bin/env python3
"""scripts/bootstrap/lib/render-verify-grid-md.py — R207 verify-grid doc renderer.

Reads config/bootstrap/verify-grid.yaml + emits
docs/src/bootstrap-verify-grid.md as an operator-readable rundown of
the master spec § 22 6-check operational grid (the grid that
sovereign-osctl bootstrap verify runs on a live node).

Usage:
  render-verify-grid-md.py             write the doc + return 0
  render-verify-grid-md.py --check     rc=1 if stale (CI gate)
  render-verify-grid-md.py --stdout    write to stdout
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
YAML_PATH = REPO_ROOT / "config" / "bootstrap" / "verify-grid.yaml"
DOC_PATH = REPO_ROOT / "docs" / "src" / "bootstrap-verify-grid.md"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/bootstrap/lib/render-verify-grid-md.py from "
    "config/bootstrap/verify-grid.yaml. Do NOT edit this file directly — "
    "edit the YAML and re-run the renderer. R207 (SDD-028 pattern). -->\n"
)


def render(doc: dict) -> str:
    grid = doc["verify_grid"]
    checks = grid["checks"]
    lines = [GENERATED_BANNER]
    lines.append(f"# {grid['spec_section']}\n")
    lines.append(grid["description"].strip() + "\n")
    lines.append(
        f"This doc is regenerated from `config/bootstrap/verify-grid.yaml` "
        "on every invocation of `scripts/bootstrap/lib/render-verify-grid-md.py`. "
        "The same YAML drives the metadata table in `scripts/bootstrap/verify.sh` "
        "via `lib/load-verify-grid.py`, so the doc and the live verifier can "
        "never drift on check IDs / names / spec citations.\n"
    )

    lines.append("## Check inventory\n")
    lines.append("| ID | Name | Master spec | Skips when |")
    lines.append("|----|------|-------------|------------|")
    for c in checks:
        lines.append(
            f"| {c['id']} | {c['name']} | {c['master_spec_section']} | {c['skip_when']} |"
        )
    lines.append("")

    for c in checks:
        lines.append(f"## Check {c['id']} — {c['name']}\n")
        lines.append(f"- **Master spec:** {c['master_spec_section']}")
        lines.append(f"- **Checks:** {c['checks_what']}")
        lines.append(f"- **Skip condition:** {c['skip_when']}")
        tools = c.get("tools_required") or []
        if tools:
            tools_str = ", ".join(f"`{t}`" for t in tools)
            lines.append(f"- **Tools required:** {tools_str}")
        else:
            lines.append("- **Tools required:** *(none — uses /proc or filesystem reads)*")
        lines.append("")

    lines.append("## Cross-references\n")
    lines.append("- `config/bootstrap/verify-grid.yaml` — canonical metadata source")
    lines.append("- `scripts/bootstrap/verify.sh` — the executor (per-check bash bodies)")
    lines.append("- `sovereign-osctl bootstrap verify [--only IDS] [--strict] [--json]` — operator surface")
    lines.append("- `sovereign-osctl bootstrap phases` — companion inventory of master spec § 12 5-phase artifacts")
    lines.append("- SDD-028 — canonical-source pattern this doc follows")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()

    if not YAML_PATH.exists():
        print(f"ERROR verify-grid.yaml not found at {YAML_PATH}", file=sys.stderr)
        return 2

    with YAML_PATH.open() as fh:
        doc = yaml.safe_load(fh)

    rendered = render(doc)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        if not DOC_PATH.exists():
            print(f"ERROR doc not present at {DOC_PATH}", file=sys.stderr)
            return 1
        if DOC_PATH.read_text() != rendered:
            print(
                "ERROR docs/src/bootstrap-verify-grid.md is stale; "
                "rerun render-verify-grid-md.py to refresh.",
                file=sys.stderr,
            )
            return 1
        print("docs/src/bootstrap-verify-grid.md is fresh")
        return 0

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(rendered)
    print(f"wrote {DOC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
