//! GENERATED by cockpit-wasm/gen-bridges.py — DO NOT EDIT BY HAND.
//! Declares the hand-written bespoke bridges (round 3 — crates without a
//! uniform validate()). The .rs files themselves are hand-authored.

pub mod aspect_ratio_box;
pub mod auto_link;
pub mod callout_arrow;
pub mod color_contrast;
pub mod day_divider;
pub mod delta_pill;
pub mod friction_audit_panel;
pub mod guardian_panel;
pub mod pagination;
pub mod perimeter_panel;
pub mod relative_time;
pub mod scheduler_panel;
pub mod search_highlight;
pub mod search_history;
pub mod shortcut_cheatsheet;
pub mod text_truncation;
pub mod toast_stack;
pub mod views;
pub mod word_count;
