#!/usr/bin/env python3
"""scripts/trinity/render-runtime-profiles-md.py — R208 runtime-profile doc renderer.

Fourth application of the SDD-028 canonical-source pattern: reads
profiles/runtime/{ultra-sovereign-efficiency,high-concurrency-burst,
deep-context-synthesis}.yaml + emits docs/src/trinity-runtime-profiles.md
as an operator-readable rundown of the master spec § 18 trinity
runtime profiles.

The same YAMLs drive:
  scripts/build/lib/runtime-profile.sh — env-first override library
  sovereign-osctl trinity profile {list,show,switch} — operator surface
  scripts/inference/start-*.sh — runtime invocation honoring

This renderer ensures the operator-facing doc can never drift from
those execution surfaces.

Usage:
  render-runtime-profiles-md.py            write doc + return 0
  render-runtime-profiles-md.py --check    rc=1 if stale (CI gate)
  render-runtime-profiles-md.py --stdout   write to stdout
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
PROFILES_DIR = REPO_ROOT / "profiles" / "runtime"
DOC_PATH = REPO_ROOT / "docs" / "src" / "trinity-runtime-profiles.md"

# Master spec § 18 chronological order.
ORDERED_IDS = (
    "ultra-sovereign-efficiency",
    "high-concurrency-burst",
    "deep-context-synthesis",
)

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/trinity/render-runtime-profiles-md.py from "
    "profiles/runtime/*.yaml. Do NOT edit this file directly — edit the "
    "YAMLs and re-run the renderer. R208 (SDD-028 pattern). -->\n"
)


def load_profiles() -> list[dict]:
    profiles: list[dict] = []
    for pid in ORDERED_IDS:
        path = PROFILES_DIR / f"{pid}.yaml"
        if not path.exists():
            raise FileNotFoundError(f"missing runtime profile YAML: {path}")
        with path.open() as fh:
            doc = yaml.safe_load(fh)
        profiles.append(doc["runtime_profile"])
    return profiles


def render(profiles: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append("# Trinity runtime profiles (master spec § 18)\n")
    lines.append(
        f"The {len(profiles)} runtime profiles describe HOW the Genesis Trinity "
        "(Pulse · Logic · Oracle) is deployed at any moment. Profiles trade "
        "between sovereignty (CPU-only / low-power) and throughput (multi-GPU "
        "concurrency / large context).\n"
    )
    lines.append(
        "This doc is regenerated from `profiles/runtime/*.yaml` on every "
        "invocation of `scripts/trinity/render-runtime-profiles-md.py`. The "
        "same YAMLs drive `sovereign-osctl trinity profile {list,show,switch}` "
        "and the inference `start-*.sh` scripts — so the doc, the switcher, "
        "and the runtime cannot drift.\n"
    )

    # Summary table
    lines.append("## Profile summary\n")
    lines.append("| ID | Name | Hardware compat | System total (W) |")
    lines.append("|----|------|-----------------|------------------|")
    for p in profiles:
        compat = ", ".join(p.get("hardware_profile_compat") or [])
        power = p.get("expected_power_draw_watts", {}).get("system_total", "—")
        lines.append(f"| `{p['id']}` | {p['name']} | {compat} | {power} |")
    lines.append("")

    # Per-profile detail
    for p in profiles:
        lines.append(f"## {p['name']}\n")
        lines.append(f"**ID:** `{p['id']}`\n")
        lines.append((p.get("description", "")).strip() + "\n")

        compat = p.get("hardware_profile_compat") or []
        if compat:
            lines.append(f"**Hardware-profile compatibility:** {', '.join(compat)}\n")

        allocations = p.get("allocations") or []
        if allocations:
            lines.append("**Trinity allocations:**\n")
            lines.append("| Agent | Tier | Target | Core mask | Engine | Model |")
            lines.append("|-------|------|--------|-----------|--------|-------|")
            for a in allocations:
                lines.append(
                    f"| `{a.get('agent_id','?')}` "
                    f"| {a.get('tier','?')} "
                    f"| {a.get('target_hardware','?')} "
                    f"| `{a.get('core_mask') or a.get('gpu_id') or '—'}` "
                    f"| `{a.get('engine','?')}` "
                    f"| `{a.get('model','?')}` |"
                )
            lines.append("")

        gpu = p.get("gpu_state") or {}
        if gpu:
            lines.append("**GPU state:**\n")
            for key in ("primary", "secondary"):
                if key in gpu:
                    g = gpu[key]
                    lines.append(
                        f"- {key.capitalize()}: `{g.get('mode','?')}` "
                        f"(invocation: `{g.get('command','—')}`)"
                    )
            lines.append("")

        power = p.get("expected_power_draw_watts") or {}
        if power:
            lines.append("**Expected power draw (W):**\n")
            for key, val in power.items():
                lines.append(f"- {key}: {val}")
            lines.append("")

        obs = p.get("observability") or {}
        if obs:
            lines.append("**Observability:**\n")
            if "primary_metric" in obs:
                lines.append(f"- Primary metric: `{obs['primary_metric']}`")
            if "expected_throughput_tokens_per_sec" in obs:
                lines.append(
                    f"- Expected throughput: {obs['expected_throughput_tokens_per_sec']} tok/s"
                )
            lines.append("")

    lines.append("## Cross-references\n")
    lines.append("- `profiles/runtime/*.yaml` — canonical sources")
    lines.append("- `schemas/runtime-profile.schema.yaml` — JSON Schema")
    lines.append("- `scripts/build/lib/runtime-profile.sh` — env-first override library")
    lines.append("- `sovereign-osctl trinity profile {list,show,switch}` — operator surface")
    lines.append("- `scripts/inference/start-{pulse,logic-engine,oracle-core}.sh` — start scripts honoring the active profile")
    lines.append("- SDD-011 — inference backend stack decision")
    lines.append("- SDD-028 — canonical-source pattern this doc follows (fourth application after phases / model-catalog / verify-grid)")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()

    try:
        profiles = load_profiles()
    except FileNotFoundError as e:
        print(f"ERROR {e}", file=sys.stderr)
        return 2

    rendered = render(profiles)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        if not DOC_PATH.exists():
            print(f"ERROR doc not present at {DOC_PATH}", file=sys.stderr)
            return 1
        if DOC_PATH.read_text() != rendered:
            print(
                "ERROR docs/src/trinity-runtime-profiles.md is stale; "
                "rerun render-runtime-profiles-md.py to refresh.",
                file=sys.stderr,
            )
            return 1
        print("docs/src/trinity-runtime-profiles.md is fresh")
        return 0

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(rendered)
    print(f"wrote {DOC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
