"""The panel's JavaScript must parse — a syntax error breaks the whole page.

2026-07-27. The build panel is 6300 lines with ~4800 lines of inline JS. A
single syntax error anywhere in it leaves the operator with a page that renders
and does nothing: no BUILD button, no log streaming, no error in the terminal
they were watching.

Several controls were added to it today. I initially reported that no JS engine
was available to check them — that was wrong; the earlier check failed because
of a `node --check <(...)` process-substitution form, not a missing node. Real
verification was available the whole time.

Also asserts the app-shell block (generated by scripts/webapp/sync-app-shell.py)
is untouched: CLAUDE.md forbids hand-editing between its markers, and the panel
edits sit outside them.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
PANEL = REPO_ROOT / "webapp" / "build-configurator" / "index.html"
BEGIN, END = "<!-- APP-SHELL:BEGIN M067 -->", "<!-- APP-SHELL:END M067 -->"


def inline_js() -> str:
    html = PANEL.read_text(encoding="utf-8")
    blocks = re.findall(r"<script(?![^>]*\bsrc=)[^>]*>(.*?)</script>", html, re.DOTALL)
    assert blocks, "no inline <script> found — did the panel change shape?"
    return "\n;\n".join(blocks)


@pytest.mark.skipif(shutil.which("node") is None, reason="node not installed")
def test_the_panels_javascript_parses(tmp_path: Path):
    js = tmp_path / "panel.js"
    js.write_text(inline_js(), encoding="utf-8")
    out = subprocess.run(["node", "--check", str(js)], capture_output=True, text=True)
    assert out.returncode == 0, f"panel JS does not parse:\n{out.stderr}"


def test_the_target_machine_block_is_present_in_the_js():
    js = inline_js()
    for field in ("tgt-hostname", "tgt-username", "tgt-cmdline",
                  "tgt-blacklist", "tgt-kdebs"):
        assert field in js, f"{field} is never read by the panel's JS"


@pytest.mark.skipif(shutil.which("node") is None, reason="node not installed")
def test_missing_elements_do_not_crash_the_request(tmp_path: Path):
    """getElementById returns null when a control is absent.

    The block must degrade to {} — an older cached page, or a future edit that
    drops a field, must not throw while assembling the build request.
    """
    js = inline_js()
    m = re.search(r"\.\.\.\(function \(\) \{.*?\}\)\(\)", js, re.DOTALL)
    assert m, "the target-machine block was not found in the panel JS"
    # The captured text is `...(function () { ... })()` — already an
    # INVOCATION. Stripping the leading "..." leaves a complete call; appending
    # another "()" invoked the RESULT and threw (2026-07-27, my own test).
    body = m.group(0)[len("..."):]
    probe = tmp_path / "probe.js"
    probe.write_text(
        "global.document={getElementById:()=>null};\n"
        f"const out={body};\n"
        "if (Object.keys(out).length !== 0) { console.error('expected {}'); process.exit(1); }\n",
        encoding="utf-8")
    out = subprocess.run(["node", str(probe)], capture_output=True, text=True)
    assert out.returncode == 0, (
        f"the target-machine block throws when controls are absent:\n{out.stderr}"
    )


def test_the_generated_app_shell_block_was_not_hand_edited():
    """CLAUDE.md: app-shell embeds go through sync-app-shell.py, never by hand."""
    html = PANEL.read_text(encoding="utf-8")
    block = html[html.index(BEGIN):html.index(END)]
    for token in ("bgrp", "bkey", "TARGET MACHINE", "tgt-hostname"):
        assert token not in block, (
            f"{token!r} was added inside the generated app-shell block; the "
            "generator will overwrite it"
        )
