"""The cockpit postinst is generated by a heredoc — so nothing checks it.

2026-07-26. This package's postinst is emitted from inside build.sh. A syntax
error, an unbound variable or a bad path in it is not caught by shellcheck (it
is a string, not a script) and surfaces only when dpkg runs it MID-INSTALL, on
the operator's machine, an hour into a build-flash-install cycle.

It also carries real logic now: the /usr/local/lib/sovereign-os compatibility
symlink (68 units ExecStart from there while the package installs to
/opt/sovereign-os) and the unit installation. Those must work, and must not
clobber a real deployment.

So: extract it, parse it, and RUN it against a throwaway root.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
BUILD = REPO_ROOT / "scripts" / "build" / "installer-cdd" / "build.sh"


def sandboxed_env(tmp_path: Path) -> dict:
    """Run the postinst with systemctl stubbed out.

    The postinst calls `systemctl daemon-reload`. Unsandboxed, this test issued
    that against the DEVELOPER'S live system — a real side effect, and it made
    a single lint take 25 seconds (2026-07-26).
    """
    import os
    bin_dir = tmp_path / "stub-bin"
    bin_dir.mkdir(exist_ok=True)
    stub = bin_dir / "systemctl"
    stub.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    stub.chmod(0o755)
    env = dict(os.environ)
    env["PATH"] = f"{bin_dir}:{env.get('PATH', '')}"
    return env


def postinst_source() -> str:
    text = BUILD.read_text(encoding="utf-8")
    marker = "<<'POSTINST'"
    assert marker in text, (
        "the postinst heredoc must stay QUOTED — unquoted, its $ and ` expand "
        "while the package is being built"
    )
    start = text.index(marker) + len(marker) + 1
    return text[start:text.index("\nPOSTINST", start)]


def test_the_generated_postinst_is_valid_shell():
    out = subprocess.run(["sh", "-n"], input=postinst_source(),
                         capture_output=True, text=True)
    assert out.returncode == 0, f"generated postinst does not parse:\n{out.stderr}"


@pytest.mark.skipif(shutil.which("sh") is None, reason="no sh")
def test_it_runs_to_completion_against_a_throwaway_root(tmp_path: Path):
    """dpkg aborts the whole install if postinst exits non-zero."""
    root = tmp_path / "root"
    for d in ("opt/sovereign-os/systemd/system", "lib/systemd/system",
              "usr/local/lib", "etc"):
        (root / d).mkdir(parents=True, exist_ok=True)
    unit = REPO_ROOT / "systemd" / "system" / "sovereign-firstboot.service"
    shutil.copy(unit, root / "opt/sovereign-os/systemd/system/")

    src = postinst_source()
    # Sandbox /var too — the postinst writes status and logs there, and the
    # test was executing those against the developer's real filesystem.
    for real in ("/opt/sovereign-os", "/etc/sovereign-os", "/usr/local/lib",
                 "/lib/systemd/system", "/var/log/sovereign-os",
                 "/var/lib/sovereign-os"):
        src = src.replace(real, f"{root}{real}")

    out = subprocess.run(["sh"], input=src, capture_output=True, text=True,
                         env=sandboxed_env(tmp_path))
    assert out.returncode == 0, (
        f"postinst exited {out.returncode} — dpkg would abort the install:\n"
        f"{out.stdout}{out.stderr}"
    )
    assert (root / "lib/systemd/system/sovereign-firstboot.service").exists(), (
        "units were not installed where systemd looks"
    )
    # The compatibility symlink is deliberately NOT made here — creating it
    # before the deploy makes install-gui-dashboards.sh copy a directory into
    # itself. deploy-dashboards.sh creates it afterwards, as a fallback.
    assert not (root / "usr/local/lib/sovereign-os").exists(), (
        "the postinst must not pre-create the app-tree path; the deploy runs "
        "later and its own logic leaves a symlink alone"
    )
    assert (root / "etc/sovereign-os/active-profile").read_text().strip() == "sain-01"


def test_it_leaves_a_real_deployment_alone(tmp_path: Path):
    """install-gui-dashboards.sh deploys the REAL app tree to that path.

    If the symlink were unconditional it would replace a good deployment with a
    link to a partial one.
    """
    root = tmp_path / "root"
    for d in ("opt/sovereign-os/systemd/system", "lib/systemd/system",
              "usr/local/lib/sovereign-os/real-tree", "etc"):
        (root / d).mkdir(parents=True, exist_ok=True)

    src = postinst_source()
    for real in ("/opt/sovereign-os", "/etc/sovereign-os",
                 "/usr/local/lib", "/lib/systemd/system"):
        src = src.replace(real, f"{root}{real}")
    subprocess.run(["sh"], input=src, capture_output=True, text=True,
                   check=False, env=sandboxed_env(tmp_path))

    target = root / "usr/local/lib/sovereign-os"
    assert target.is_dir() and not target.is_symlink(), (
        "the postinst replaced a real app-tree deployment with a symlink"
    )
    assert (target / "real-tree").exists(), "the existing deployment was destroyed"
