#!/usr/bin/env python3
"""tests/lint/test_panel_api_routes.py — the :8100 hub's panel-API routing.

`config/panel-api-routes.yaml` is generated by
`scripts/operator/gen-panel-routes.py` from every `scripts/operator/*-api.py`,
so the dev hub proxies EVERY panel's `/api/…` calls — not the 4 hand-picked
prefixes it listed before, which left `/api/control/execute`,
`/api/code-console/chat`, and ~50 per-panel data endpoints 404'd (the
interactive control surface was dead on the documented `make panel` path).

This lint keeps it honest:
  * regen-and-compare — the committed registry equals a fresh generation;
  * the control + code-console + a sample of data routes are actually present;
  * the hub loads the registry and its `_route_for` matches prefixes precisely;
  * the hub's do_POST proxies non-local /api routes (the dead-surface fix).
"""
from __future__ import annotations

import importlib.util
import re
from pathlib import Path

import pytest

yaml = pytest.importorskip("yaml")

REPO = Path(__file__).resolve().parents[2]
GEN = REPO / "scripts" / "operator" / "gen-panel-routes.py"
OUT = REPO / "config" / "panel-api-routes.yaml"
HUB = REPO / "scripts" / "operator" / "build-configurator-api.py"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generator_and_registry_exist():
    assert GEN.is_file() and OUT.is_file()


def test_registry_is_not_stale():
    gen = _load("gen_panel_routes", GEN)
    expected = gen.render()
    assert OUT.read_text(encoding="utf-8") == expected, (
        f"{OUT.relative_to(REPO)} is stale — regenerate with "
        f"python3 {GEN.relative_to(REPO)} (a panel API was added/renamed)"
    )


def _routes() -> dict[str, int]:
    doc = yaml.safe_load(OUT.read_text(encoding="utf-8"))
    return {r["prefix"]: r["port"] for r in doc["routes"]}


def test_dead_interactive_routes_now_covered():
    """The exact routes the audit found 404'ing — the interactive surface."""
    routes = _routes()
    assert routes.get("/api/control") == 8130, "control-exec (execute/registry) unmapped"
    assert routes.get("/api/code-console") == 8140, "code-console (ask AI) unmapped"


def test_a_sample_of_per_panel_data_routes_covered():
    routes = _routes()
    # a spread of per-panel data endpoints that were 404'ing via the hub
    for prefix in ("/api/evals", "/api/lm-status", "/api/adapters", "/api/costs"):
        assert prefix in routes, f"{prefix} data endpoint not proxied by the hub"


def test_hub_local_endpoints_are_not_proxied():
    """/api/run + /api/cancel are the hub's OWN build/flash console — proxying
    them would loop back onto the hub. They must be absent from the registry."""
    routes = _routes()
    assert "/api/run" not in routes and "/api/cancel" not in routes


def test_no_prefix_maps_to_two_ports():
    doc = yaml.safe_load(OUT.read_text(encoding="utf-8"))
    seen: dict[str, int] = {}
    for r in doc["routes"]:
        assert r["prefix"] not in seen or seen[r["prefix"]] == r["port"], (
            f"{r['prefix']} maps to two ports — a real routing collision"
        )
        seen[r["prefix"]] = r["port"]


def test_hub_loads_registry_and_route_for_matches_precisely():
    hub = _load("build_configurator_api", HUB)
    routes = hub._load_panel_routes()
    # generated routes are present, plus node_exporter
    assert routes.get("/api/control") == 8130
    assert routes.get("/api/node-exporter") == 9100
    # precise segment matching — not a bare startswith
    assert hub._route_for("/api/control") == 8130
    assert hub._route_for("/api/control/execute") == 8130
    assert hub._route_for("/api/controlX") is None, "must not over-match a prefix"
    assert hub._route_for("/api/nonexistent/x") is None


def test_hub_do_post_proxies_non_local_api_routes():
    """Regression guard: do_POST must proxy /api/<prefix> POSTs (the fix). A
    refactor that drops it re-breaks /api/control/execute + code-console/chat."""
    body = HUB.read_text(encoding="utf-8")
    # the proxy dispatch calls _route_for then _proxy(..., "POST", ...)
    assert re.search(r"_route_for\(path\)", body)
    assert re.search(r'_proxy\([^\n]*"POST"', body), (
        "do_POST no longer forwards POST bodies to the backing API"
    )
    # and _proxy forwards a body + method (POST support present)
    assert "method: str = \"GET\"" in body and "data=body if method" in body
