"""Backlog delivery roll-up sync contract (F-2026-038 / SDD-972).

`backlog/SHIPPED-ROLLUP.md` is generated by `scripts/backlog/gen-shipped-rollup.py`
from the milestone files (catalogued R-rows) + `backlog/SHIPPED.md` (delivery records),
so "how done is M0xx" is queryable instead of the old SAMPLED / state-TBD snapshot.

This lint keeps it honest:
  * regen-and-compare — the committed roll-up must equal a fresh generation, so it can't
    silently drift when a milestone or SHIPPED.md changes;
  * completeness — every milestone file appears in the roll-up.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GEN = REPO_ROOT / "scripts" / "backlog" / "gen-shipped-rollup.py"
OUT = REPO_ROOT / "backlog" / "SHIPPED-ROLLUP.md"
MILESTONES = REPO_ROOT / "backlog" / "milestones"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_shipped_rollup", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generator_and_output_exist():
    assert GEN.is_file(), f"missing {GEN}"
    assert OUT.is_file(), f"missing {OUT} — run `python3 {GEN.relative_to(REPO_ROOT)}`"


def test_rollup_is_not_stale():
    mod = _load_generator()
    expected = mod.render()
    actual = OUT.read_text(encoding="utf-8")
    assert actual == expected, (
        f"{OUT.relative_to(REPO_ROOT)} is stale — regenerate with "
        f"`python3 {GEN.relative_to(REPO_ROOT)}` after backlog/milestones or SHIPPED.md changes"
    )


def test_every_milestone_is_in_the_rollup():
    body = OUT.read_text(encoding="utf-8")
    missing = []
    for f in sorted(MILESTONES.glob("M*.md")):
        if f.name == "INDEX.md":
            continue
        mid = f.name.split("-", 1)[0]
        if f"| {mid} |" not in body:
            missing.append(mid)
    assert not missing, f"milestones missing from the roll-up: {missing}"
