"""Cockpit consumption-map sync contract (2026-07-17).

`docs/cockpit/consumption-map.md` is generated by
`scripts/cockpit/gen-consumption-map.py` from the crate tree + cockpit-wasm
bridges + Cargo dependency graph, so "which cockpit crates are actually
consumed vs compiled-and-tested-only" is a queryable, always-current fact
instead of a claim that rots. Same regen-and-compare discipline as the backlog
INDEX / SHIPPED-ROLLUP generators.

The map is the NON-DESTRUCTIVE answer to the ~380-shelfware audit finding: the
"we do not minimize" doctrine forbids deleting the crates, so instead the map
makes the wire-or-retire backlog visible + locked. This lint keeps it honest:
  * regen-and-compare — committed map == fresh generation;
  * every cockpit crate is classified (no crate silently missing);
  * the tier counts sum to the crate total (classification is a partition).
"""
from __future__ import annotations

import importlib.util
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GEN = REPO / "scripts" / "cockpit" / "gen-consumption-map.py"
OUT = REPO / "docs" / "cockpit" / "consumption-map.md"
CRATES = REPO / "crates"
PREFIX = "sovereign-cockpit-"


def _load():
    spec = importlib.util.spec_from_file_location("gen_cockpit_map", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generator_and_output_exist():
    assert GEN.is_file(), f"missing {GEN}"
    assert OUT.is_file(), f"missing {OUT} — run python3 {GEN.relative_to(REPO)}"


def test_map_is_not_stale():
    mod = _load()
    expected = mod.render()
    actual = OUT.read_text(encoding="utf-8")
    assert actual == expected, (
        f"{OUT.relative_to(REPO)} is stale — regenerate with "
        f"python3 {GEN.relative_to(REPO)} (a cockpit crate was added/removed "
        f"or its consumption changed)"
    )


def test_every_cockpit_crate_is_classified():
    mod = _load()
    crates = mod._cockpit_crates()
    tier, _ = mod._classify(crates)
    assert set(tier) == set(crates), "a cockpit crate went unclassified"
    assert all(
        t in ("wasm-compute", "rust-consumer", "validate-bridge", "compiled-only")
        for t in tier.values()
    )


def test_headline_counts_partition_the_family():
    """live + export-only + compiled-only == total crates (a partition —
    no crate double-counted or dropped)."""
    body = OUT.read_text(encoding="utf-8")
    m = re.search(
        r"\*\*(\d+) cockpit crates\*\* · \*\*(\d+) live-consumed\*\*.*?"
        r"\*\*(\d+) export-only\*\*.*?\*\*(\d+) compiled-only\*\*",
        body, re.S,
    )
    assert m, "headline counts line missing/!changed shape"
    total, live, export_only, compiled_only = (int(m.group(i)) for i in range(1, 5))
    n_crates = len([p for p in CRATES.glob(f"{PREFIX}*") if (p / "Cargo.toml").is_file()])
    assert total == n_crates, f"map says {total} crates; tree has {n_crates}"
    assert live + export_only + compiled_only == total, (
        f"tiers {live}+{export_only}+{compiled_only} != {total} (not a partition)"
    )
