"""crate-inventory sync lint (F-2026-098 / SDD-995).

`scripts/docs/gen-crate-inventory.py` generates `docs/architecture/crate-inventory.md`
(the complete map of every workspace crate + whether anything reaches it). It was
the **one** generated-doc script without a `--check` freshness gate — so a crate
added or removed from the workspace could silently leave the inventory stale, the
exact living-doc drift the audit warns about and that gen-sdd-catalog.py (SDD-958) /
the counts-contract (SDD-952) / the island register (SDD-955) already guard.

SDD-995 adds `render()` + a `--check` mode to the generator; this lint runs the
generator in-process and fails if the committed page has drifted from the tree — so
the inventory can only be regenerated, never hand-edited, and a crate churn that
isn't reflected is caught in CI.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GEN = REPO_ROOT / "scripts" / "docs" / "gen-crate-inventory.py"
INVENTORY = REPO_ROOT / "docs" / "architecture" / "crate-inventory.md"


def _load_generator():
    spec = importlib.util.spec_from_file_location("_gen_crate_inventory", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generator_script_exists():
    assert GEN.is_file(), f"missing generator {GEN}"


def test_generator_exposes_render_and_check():
    gen = _load_generator()
    assert hasattr(gen, "render"), "gen-crate-inventory.py must expose render() for the sync lint"
    src = GEN.read_text(encoding="utf-8")
    assert "--check" in src, "gen-crate-inventory.py must support --check (CI freshness gate)"


def test_crate_inventory_is_in_sync_with_the_workspace():
    gen = _load_generator()
    expected = gen.render()
    actual = INVENTORY.read_text(encoding="utf-8") if INVENTORY.exists() else ""
    assert actual == expected, (
        "docs/architecture/crate-inventory.md is out of date with the crate tree — "
        "run `python3 scripts/docs/gen-crate-inventory.py` (do not hand-edit it). "
        "A crate was added/removed/re-described without regenerating the inventory."
    )


def test_inventory_marks_itself_generated():
    body = INVENTORY.read_text(encoding="utf-8")
    assert "GENERATED by `scripts/docs/gen-crate-inventory.py`" in body, (
        "the inventory must carry its do-not-hand-edit generated banner"
    )
