"""R370 (E10.M14) — verbatim-surface.md drift detector.

Ensures `docs/src/verbatim-surface.md` stays in sync with the underlying
Python catalog files. The doc is the operator-readable render of the
SDD-037 verbatim surface (`scripts/intelligence/verbatim-render.py
render`). If an agent adds a new C-NN concept or A-NN axis without
regenerating the doc, this lint catches the drift at push-time.

Drift detection strategy:
- Item-count consistency: doc must contain ≥ as many catalog IDs as
  the live catalogs do (item-by-item presence). If catalog grows, doc
  must grow too.
- Section presence: doc must contain headers for every catalog the
  render emits (§13, §14, concepts, axes, §19.2 CCD, §7.1, §7.2, §8,
  REPL).
- Top title intact: doc starts with the expected H1 from
  verbatim-render.
- Last-updated marker: doc carries the generator footer crediting
  verbatim-render.

To regenerate: `python3 scripts/intelligence/verbatim-render.py render
> docs/src/verbatim-surface.md`
"""
from __future__ import annotations

import importlib.util
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SURFACE_DOC = REPO_ROOT / "docs" / "src" / "verbatim-surface.md"
ARCH_QA = REPO_ROOT / "scripts" / "intelligence" / "architecture-qa.py"
COVERAGE = REPO_ROOT / "scripts" / "intelligence" / "coverage-map.py"


def _load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_surface_doc_exists():
    assert SURFACE_DOC.is_file(), (
        f"missing {SURFACE_DOC}. Regenerate via:\n"
        "  python3 scripts/intelligence/verbatim-render.py render "
        "> docs/src/verbatim-surface.md"
    )


def test_surface_doc_has_top_title():
    body = SURFACE_DOC.read_text(encoding="utf-8")
    assert body.startswith("# Sovereign-OS verbatim-preservation surface"), (
        "verbatim-surface.md missing expected top H1; regenerate the doc"
    )


def test_surface_doc_has_required_section_headers():
    body = SURFACE_DOC.read_text(encoding="utf-8")
    required = [
        "## Catalog tally",
        "## §13 Architectural Q&A Matrix",
        "## §14 Critical Edge Cases & Operational Gotchas",
        "## Architecture-qa concepts",
        "## Coverage-map axes",
        "## §19.2 CCD pinning",
        "## §7.1 State fabric file-state matrix",
        "## §7.2 State fabric ZFS transactional optimizations",
        "## §8 Network topology",
        "## Multi-level REPL modes",
    ]
    missing = [s for s in required if s not in body]
    assert not missing, (
        f"verbatim-surface.md missing required headers: {missing}. "
        "Regenerate the doc."
    )


def test_surface_doc_contains_every_concept_id():
    """Every C-NN in the architecture-qa catalog must appear in the doc.
    Drift catch: agent added C-24 concept but forgot to regenerate."""
    mod = _load_module(ARCH_QA, "verbatim_surface_concept_drift")
    body = SURFACE_DOC.read_text(encoding="utf-8")
    missing = []
    for c in mod.ARCHITECTURE_CONCEPTS:
        cid = c.get("id")
        if cid and f"### {cid}" not in body:
            missing.append(cid)
    assert not missing, (
        f"verbatim-surface.md missing concept ID headers: {missing}. "
        f"Regenerate via:\n  python3 scripts/intelligence/verbatim-render.py "
        f"render > docs/src/verbatim-surface.md"
    )


def test_surface_doc_contains_every_axis_id():
    """Every A-NN in the coverage-map catalog must appear in the doc."""
    mod = _load_module(COVERAGE, "verbatim_surface_axis_drift")
    body = SURFACE_DOC.read_text(encoding="utf-8")
    missing = []
    for a in mod.DEFAULT_AXES:
        aid = a.get("id")
        if aid and aid not in body:
            missing.append(aid)
    assert not missing, (
        f"verbatim-surface.md missing axis IDs: {missing}. Regenerate "
        "the doc."
    )


def test_surface_doc_contains_every_question_and_gotcha_id():
    mod = _load_module(ARCH_QA, "verbatim_surface_q_g_drift")
    body = SURFACE_DOC.read_text(encoding="utf-8")
    missing = []
    for q in mod.ARCHITECTURE_QUESTIONS:
        qid = q.get("id")
        if qid and qid not in body:
            missing.append(qid)
    for g in mod.ARCHITECTURE_GOTCHAS:
        gid = g.get("id")
        if gid and gid not in body:
            missing.append(gid)
    assert not missing, (
        f"verbatim-surface.md missing Q-NN or G-NN IDs: {missing}. "
        "Regenerate the doc."
    )


def test_surface_doc_carries_generator_footer():
    body = SURFACE_DOC.read_text(encoding="utf-8")
    assert "Generated by" in body and "sovereign-osctl verbatim-render" in body, (
        "verbatim-surface.md missing generator footer; regenerate"
    )


def test_summary_md_lists_surface_doc():
    """The mdbook SUMMARY.md must include a link to verbatim-surface.md
    so it's published in the operator-readable doc tree."""
    summary = (REPO_ROOT / "docs" / "src" / "SUMMARY.md").read_text(
        encoding="utf-8")
    assert "verbatim-surface.md" in summary, (
        "docs/src/SUMMARY.md does not link to verbatim-surface.md — "
        "operator-readable doc tree drops it from mdbook publishing. "
        "Add a row to SUMMARY.md."
    )


def test_surface_doc_total_items_matches_summary():
    """Doc's tally section must show non-zero totals (sanity check
    that the doc was generated against a real catalog, not stale)."""
    body = SURFACE_DOC.read_text(encoding="utf-8")
    # Tally block shape: "  **Total verbatim items**: <N>"
    m = re.search(r"\*\*Total verbatim items\*\*:\s*(\d+)", body)
    assert m, "Total verbatim items line missing in tally section"
    total = int(m.group(1))
    assert total >= 70, (
        f"verbatim-surface.md tally shows only {total} items but the "
        "SDD-037 floor is ≥70. Either regenerate the doc or extend "
        "the catalog."
    )
