"""Dashboard-routes sync contract (F-2026-072, 2026-07-17).

`config/dashboard-routes.yaml` is the master-dashboard reverse-proxy aggregator's
route table. It used to be a 26-entry hand-maintained dict inside
scripts/operator/master-dashboard.py that went stale against the 55-panel
reality (the ~29 non-`d` panels + d-21..d-29 were reachable only via the :8100
static hub, invisible to the aggregator). It is now GENERATED by
scripts/operator/gen-dashboard-routes.py — joining config/dashboard-catalog.yaml
(the authoritative panel list) with each panel API's own listen port — and
drift-locked here, the same regen-and-compare discipline as panel-api-routes.yaml
/ the backlog INDEX / the cockpit consumption map.

This lint keeps it honest:
  * regen-and-compare — committed table == fresh generation;
  * every api-backed catalog panel is either routed or explicitly skipped
    (no panel silently dropped — "we do not minimize");
  * routes are collision-free (the aggregator refuses to render otherwise);
  * master-dashboard.py loads the generated table (not a stale inline dict).
"""
from __future__ import annotations

import importlib.util
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GEN = REPO / "scripts" / "operator" / "gen-dashboard-routes.py"
OUT = REPO / "config" / "dashboard-routes.yaml"
CATALOG = REPO / "config" / "dashboard-catalog.yaml"
MD_PY = REPO / "scripts" / "operator" / "master-dashboard.py"
API_DIR = REPO / "scripts" / "operator"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generator_and_output_exist():
    assert GEN.is_file(), f"missing {GEN}"
    assert OUT.is_file(), f"missing {OUT} — run python3 {GEN.relative_to(REPO)}"


def test_table_is_not_stale():
    gen = _load("gen_dashboard_routes", GEN)
    expected = gen.render()
    actual = OUT.read_text(encoding="utf-8")
    assert actual == expected, (
        f"{OUT.relative_to(REPO)} is stale — regenerate with "
        f"python3 {GEN.relative_to(REPO)} (a panel API was added/renamed or an "
        f"infra upstream changed)"
    )


def _parse_routes() -> list[dict]:
    body = OUT.read_text(encoding="utf-8")
    start = body.index("\nroutes:")
    section = body[start:]
    end = section.find("\nstatic_only:")
    if end != -1:
        section = section[:end]
    rows = []
    for m in re.finditer(
        r'- \{slug: ([^,]+), port: (\d+),.*?subpath: "([^"]+)"', section
    ):
        rows.append({"slug": m.group(1), "port": int(m.group(2)),
                     "subpath": m.group(3)})
    return rows


def test_routes_are_collision_free():
    """port/subpath/slug are each unique — the aggregator refuses to render a
    colliding table, so a generated collision would break rendering."""
    rows = _parse_routes()
    _NETWORKING_TRIPLET = {"network-edge", "edge-firewall", "d-12-networking"}
    for key in ("slug", "port", "subpath"):
        seen: dict = {}
        for r in rows:
            seen.setdefault(r[key], []).append(r["slug"])
        dupes = {k: v for k, v in seen.items() if len(v) > 1}
        # F-2026-070: the unified networking-api intentionally serves three
        # concern-distinct panels from one port.
        if key == "port":
            dupes = {
                k: v for k, v in dupes.items()
                if not set(v).issubset(_NETWORKING_TRIPLET)
            }
        assert not dupes, f"{key} collision in dashboard-routes.yaml: {dupes}"


def test_every_api_backed_panel_is_routed_or_skipped():
    """Partition guard: every catalog panel that declares an api resolves to
    exactly one of routed / skipped / the hub itself — none silently dropped."""
    gen = _load("gen_dashboard_routes2", GEN)
    data = gen.build()
    routed = {r["slug"] for r in data["routes"]}
    static = {s["slug"] for s in data["static_only"]}
    skipped = {s["slug"] for s in data["skipped"]}

    # Re-parse the catalog panel slugs + whether each declares an api.
    cat = CATALOG.read_text(encoding="utf-8")
    body = cat[cat.index("\ndashboards:"):]
    for blob in re.findall(r"- \{(.*?)\}", body, re.DOTALL):
        e = gen._parse_entry(blob)
        slug = e.get("slug")
        if not slug:
            continue
        if e.get("api") and e["api"] != gen.HUB_API:
            assert slug in routed or slug in skipped, (
                f"catalog panel {slug!r} declares an api but is neither routed "
                f"nor skipped — it was silently dropped"
            )
        elif not e.get("api"):
            assert slug in static, (
                f"catalog panel {slug!r} has no api but is not listed under "
                f"static_only — operator can't see it"
            )


def test_infra_routes_preserved():
    """The non-panel infra upstreams (Trinity tiers, router daemon, grafana,
    node_exporter) must all be present — 'we do not minimize' the aggregator."""
    routed = {r["slug"] for r in _parse_routes()}
    for slug in ("trinity-pulse", "trinity-logic-engine", "trinity-oracle-core",
                 "router-engine", "grafana-dashboard", "metrics-textfile-collector"):
        assert slug in routed, f"infra upstream {slug!r} dropped from the table"


def test_master_dashboard_loads_generated_table():
    """The aggregator module must LOAD the generated table (not carry a stale
    inline dict) — the whole point of the reconciliation."""
    body = MD_PY.read_text(encoding="utf-8")
    assert "dashboard-routes.yaml" in body, (
        "master-dashboard.py must reference the generated dashboard-routes.yaml"
    )
    assert "def _load_routes" in body, "master-dashboard.py must load the table"
    md = _load("_md_for_routes", MD_PY)
    # Loaded table matches the committed file's route count.
    assert len(md.DASHBOARD_ROUTES) == len(_parse_routes()), (
        "loaded DASHBOARD_ROUTES count != committed dashboard-routes.yaml"
    )
