#!/usr/bin/env python3
"""gen-bridges.py — generate the uniform `<slug>_validate` wasm bridges for the
sovereign-cockpit-* crate family (audit F-2026-001 / SDD-974).

~399 cockpit crates share the exact shape `Type::validate(&self) -> Result<(), E>`
on a serde-`Deserialize` primary type. This scans them, and for each ELIGIBLE
crate emits one `bridge_validate!(<slug>_validate, sovereign_cockpit_<slug>::Type)`
line into `src/bridges.rs` (the macro compiles the crate's real validate() into
the wasm) + a path-dep into Cargo.toml's generated block.

Deterministic + idempotent: re-running produces byte-identical output for the
same `--count`. Rounds = bump `--count` (crates are bridged in sorted order), so
progress is incremental + reviewable. `--count all` bridges every eligible crate.

  python3 cockpit-wasm/gen-bridges.py --count 60     # round: first 60 eligible
  python3 cockpit-wasm/gen-bridges.py --count all    # everything eligible

Ineligible crates (no `validate(&self)`, extra-arg validate, or a non-Deserialize
primary type) are reported and skipped — they get bespoke bridges in a later round.
`sovereign-cockpit-banner-state` is excluded here (hand-bridged in lib.rs).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
CRATES = REPO / "crates"
BRIDGES_RS = HERE / "src" / "bridges.rs"
CARGO = HERE / "Cargo.toml"

DEP_BEGIN = "# BEGIN generated cockpit bridge deps (cockpit-wasm/gen-bridges.py — do not hand-edit)"
DEP_END = "# END generated cockpit bridge deps"
FEAT_BEGIN = "# BEGIN generated cockpit bridge feature (cockpit-wasm/gen-bridges.py — do not hand-edit)"
FEAT_END = "# END generated cockpit bridge feature"
EXCLUDE = {"sovereign-cockpit-banner-state"}  # hand-bridged in lib.rs


def primary_validate_type(src: str) -> str | None:
    """The type whose impl block has `pub fn validate(&self) -> Result<(),` with
    NO extra args, and which derives Deserialize. None if ineligible."""
    # walk each `impl <Type> {` block; find one containing the uniform validate
    cand = None
    for m in re.finditer(r"impl\s+(\w+)\s*\{", src):
        start = m.end()
        nxt = src.find("\nimpl ", start)
        block = src[start : nxt if nxt > 0 else len(src)]
        if re.search(r"pub fn validate\s*\(\s*&self\s*\)\s*->\s*Result<\(\)\s*,", block):
            cand = m.group(1)
            break
    if not cand:
        return None
    # the primary type must be a serde-Deserialize struct/enum
    decl = re.search(
        r"((?:#\[[^\]]*\]\s*)+)pub\s+(?:struct|enum)\s+" + re.escape(cand) + r"\b",
        src,
    )
    if not decl or "Deserialize" not in decl.group(1):
        return None
    return cand


def eligible_crates() -> tuple[list[tuple[str, str, str]], list[str]]:
    """Returns (bridged, skipped). bridged = [(slug, crate_ident, Type)] sorted."""
    bridged, skipped = [], []
    for d in sorted(CRATES.glob("sovereign-cockpit-*")):
        name = d.name
        if name in EXCLUDE:
            continue
        lib = d / "src" / "lib.rs"
        if not lib.is_file():
            skipped.append(name)
            continue
        ty = primary_validate_type(lib.read_text(errors="ignore"))
        if not ty:
            skipped.append(name)
            continue
        slug = name[len("sovereign-cockpit-") :]
        bridged.append((slug, name.replace("-", "_"), ty))
    return bridged, skipped


def render_bridges_rs(rows: list[tuple[str, str, str]]) -> str:
    lines = [
        "//! GENERATED by cockpit-wasm/gen-bridges.py — DO NOT EDIT BY HAND.",
        "//!",
        "//! One `<slug>_validate(json)` wasm export per uniform cockpit crate; each",
        "//! runs that crate's REAL `validate()` in the browser (audit F-2026-001).",
        "//! Regenerate: `python3 cockpit-wasm/gen-bridges.py --count <N|all>` then `cargo fmt`.",
        "",
        "use wasm_bindgen::prelude::wasm_bindgen;",
        "",
    ]
    for slug, ident, ty in rows:
        fn = slug.replace("-", "_") + "_validate"
        lines.append(f"crate::bridge_validate!({fn}, {ident}::{ty});")
    lines.append("")
    return "\n".join(lines)


BESPOKE_DIR = HERE / "src" / "bespoke"


def bespoke_modules() -> tuple[list[str], set[str]]:
    """Scan src/bespoke/*.rs (hand-written, round 3): returns (module stems sorted,
    the set of sovereign-cockpit-* crate NAMES they import). These crates lack the
    uniform validate() so they are bridged by hand, but still need their optional
    dep + feature entry — picked up here so a bespoke import (e.g. keystroke-map)
    can never be forgotten."""
    stems, crates = [], set()
    if not BESPOKE_DIR.is_dir():
        return stems, crates
    for f in sorted(BESPOKE_DIR.glob("*.rs")):
        if f.name == "mod.rs":
            continue
        stems.append(f.stem)
        for ident in re.findall(r"use sovereign_cockpit_(\w+)::", f.read_text(errors="ignore")):
            crates.add("sovereign-cockpit-" + ident.replace("_", "-"))
    return stems, crates


def render_bespoke_mod(stems: list[str]) -> str:
    lines = [
        "//! GENERATED by cockpit-wasm/gen-bridges.py — DO NOT EDIT BY HAND.",
        "//! Declares the hand-written bespoke bridges (round 3 — crates without a",
        "//! uniform validate()). The .rs files themselves are hand-authored.",
        "",
    ]
    lines += [f"pub mod {s};" for s in stems]
    lines.append("")
    return "\n".join(lines)


def render_deps(crate_names: list[str]) -> str:
    # Optional deps: the default (demo) build stays banner-only + small; the full
    # bridge compiles under `--features bridges` (built on demand, not committed).
    out = [DEP_BEGIN]
    for crate in crate_names:
        out.append(f'{crate} = {{ path = "../crates/{crate}", optional = true }}')
    out.append(DEP_END)
    return "\n".join(out)


def render_feature(crate_names: list[str]) -> str:
    out = [FEAT_BEGIN, "bridges = ["]
    out += [f'    "dep:{c}",' for c in crate_names]
    out.append("]")
    out.append(FEAT_END)
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", default="all", help="N eligible crates (sorted) or 'all'")
    args = ap.parse_args()

    bridged, skipped = eligible_crates()
    total_eligible = len(bridged)
    if args.count != "all":
        bridged = bridged[: int(args.count)]

    BRIDGES_RS.write_text(render_bridges_rs(bridged), encoding="utf-8")

    besp_stems, besp_crates = bespoke_modules()
    (BESPOKE_DIR / "mod.rs").write_text(render_bespoke_mod(besp_stems), encoding="utf-8")

    # dep + feature set = the uniform bridged crates ∪ the bespoke-imported crates
    uniform_names = {"sovereign-cockpit-" + slug for slug, _i, _t in bridged}
    crate_names = sorted(uniform_names | besp_crates)

    cargo = CARGO.read_text(encoding="utf-8")
    cargo = re.sub(
        re.escape(DEP_BEGIN) + r".*?" + re.escape(DEP_END),
        render_deps(crate_names),
        cargo,
        flags=re.S,
    )
    cargo = re.sub(
        re.escape(FEAT_BEGIN) + r".*?" + re.escape(FEAT_END),
        render_feature(crate_names),
        cargo,
        flags=re.S,
    )
    CARGO.write_text(cargo, encoding="utf-8")

    print(f"bridged {len(bridged)}/{total_eligible} uniform + {len(besp_stems)} bespoke "
          f"(+ banner-state hand-bridged); {len(crate_names)} cockpit deps total")
    if skipped:
        print("ineligible-for-uniform:", ", ".join(s[len('sovereign-cockpit-'):] for s in skipped))
    return 0


if __name__ == "__main__":
    sys.exit(main())
