#!/usr/bin/env python3
"""gen-panel-routes.py — generate config/panel-api-routes.yaml (2026-07-17).

The :8100 dev hub (build-configurator-api) serves all 61 panels statically but
proxied only 4 of the ~59 panel-API route prefixes — so `/api/control/execute`,
`/api/code-console/chat`, and ~50 per-panel data endpoints 404'd in every panel,
and the interactive control surface + per-panel "ask AI" were dead on the
documented `make panel` path. This generator builds the COMPLETE prefix→port
route table the hub proxies from, so a new panel-API's routes are covered
automatically (and a lint keeps it current).

How it maps: each `scripts/operator/<name>-api.py` declares its listen port via
`os.environ.get("<X>_PORT", "NNNN")` and serves a small set of `/api/<prefix>`
routes (string literals in its handler). We join those. The hub itself
(build-configurator-api) is excluded — it is the proxy, not a backing target —
and its own action endpoints (`/api/run`, `/api/cancel`) are served locally, so
they are never proxied. A prefix that resolves to two different ports is a hard
error (a real routing collision to resolve, not something to paper over).

Run `python3 scripts/operator/gen-panel-routes.py`; `--check` exits non-zero if
the committed registry is stale. tests/lint/test_panel_api_routes.py enforces it.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
API_DIR = REPO / "scripts" / "operator"
OUT = REPO / "config" / "panel-api-routes.yaml"

# The hub itself — the proxy, never a backing target.
HUB = "build-configurator-api"
# Endpoints the hub serves LOCALLY (its own build/flash run console); never proxy.
HUB_LOCAL_PREFIXES = {"/api/run", "/api/cancel"}
# Special-cased prefixes handled outside the panel-API scan: node_exporter is a
# fixed :9100 target the hub hardcodes (build-configurator-api `_NODE_EXPORTER`),
# and master-dashboard-api PROXIES /api/node-exporter/metrics to it (F-2026-071).
# That proxy path must NOT register /api/node-exporter → master-dashboard's own
# port — the prefix belongs to node_exporter, not a panel API.
SPECIAL_PREFIXES = {"/api/node-exporter"}
# Superseded by the unified networking-api (F-2026-070). Their prefixes
# are served by the unified daemon; registering them here would collide.
SUPERSEDED = {"network-edge-api", "edge-firewall-api", "rules-mirror-api"}

_PORT_RE = re.compile(r'_PORT",\s*"(\d+)"')
_PREFIX_RE = re.compile(r'"(/api/[a-z0-9][a-z0-9-]*)')


def _api_files() -> list[Path]:
    return sorted(
        p for p in API_DIR.glob("*-api.py")
        if p.stem != HUB and p.stem not in SUPERSEDED
    )


def build_routes() -> dict[str, dict]:
    """prefix → {"port": int, "api": "sovereign-<name>-api"}."""
    routes: dict[str, dict] = {}
    collisions: list[str] = []
    for f in _api_files():
        src = f.read_text(encoding="utf-8")
        m = _PORT_RE.search(src)
        if not m:
            continue  # no static default port (m060/ms022 read from env only)
        port = int(m.group(1))
        service = f"sovereign-{f.stem}"
        for prefix in sorted(set(_PREFIX_RE.findall(src))):
            if prefix in HUB_LOCAL_PREFIXES or prefix in SPECIAL_PREFIXES:
                continue
            existing = routes.get(prefix)
            if existing and existing["port"] != port:
                collisions.append(
                    f"{prefix}: {existing['api']}:{existing['port']} vs {service}:{port}"
                )
                continue
            routes[prefix] = {"port": port, "api": service}
    if collisions:
        raise SystemExit(
            "panel-API route collisions (a prefix maps to two ports):\n  "
            + "\n  ".join(collisions)
        )
    return routes


def render() -> str:
    routes = build_routes()
    lines = [
        "# config/panel-api-routes.yaml — GENERATED by",
        "# scripts/operator/gen-panel-routes.py (CI-locked by",
        "# tests/lint/test_panel_api_routes.py). The :8100 dev hub proxies these",
        "# prefix→port routes so every panel's /api/... calls reach their backing",
        "# sovereign-*-api. Regenerate after adding/renaming a panel API:",
        "#   python3 scripts/operator/gen-panel-routes.py",
        "",
        'schema_version: "1.0.0"',
        "",
        "routes:",
    ]
    for prefix in sorted(routes):
        r = routes[prefix]
        lines.append(f'  - {{prefix: "{prefix}", port: {r["port"]}, api: {r["api"]}}}')
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != content:
            print(
                f"STALE: {OUT.relative_to(REPO)} — regenerate with "
                f"python3 scripts/operator/gen-panel-routes.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUT.relative_to(REPO)} is current")
        return 0
    OUT.write_text(content, encoding="utf-8")
    n = content.count("- {prefix:")
    print(f"wrote {OUT.relative_to(REPO)} ({n} routes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
