#!/usr/bin/env bash
# scripts/operator/operator-sudoers.sh — install a SCOPED, reviewable NOPASSWD
# sudoers drop-in so the operator (and the panel APIs + the AI agent, which all
# run as the operator user) can run the SPECIFIC privileged commands the
# sovereign-os build / verify / diagnose workflows need — without a password
# prompt. This is deliberately an allow-list, never `ALL`.
#
#   ⚡ Review first (writes nothing):   scripts/operator/operator-sudoers.sh --print
#   Install:                            sudo scripts/operator/operator-sudoers.sh   (or: make operator-sudo)
#   Remove:                             sudo scripts/operator/operator-sudoers.sh --uninstall
#   Verify current state:               scripts/operator/operator-sudoers.sh --check
#
# SECURITY: NOPASSWD on any command is a real grant. The commands here are
# scoped to two buckets:
#   • diagnostics — read-only hardware/system probes (low risk)
#   • image       — loop-mount + inspect a built image (losetup/mount/umount:
#                   powerful, but needed to VERIFY an image before flashing)
# Raw `dd` and blanket `systemctl start/stop` are intentionally NOT granted —
# flashing stays the gated `sovereign-osctl install image` path you run
# deliberately. Comment out any line below you don't want. Enroll a different
# user with SOVEREIGN_OS_OPERATOR_USER=<name>.
set -euo pipefail

DEST="/etc/sudoers.d/sovereign-os-operator"
OPERATOR="${SOVEREIGN_OS_OPERATOR_USER:-${SUDO_USER:-$(id -un)}}"
# Granting NOPASSWD to root is meaningless (root already has everything). When
# the script is run DIRECTLY as root (no SUDO_USER), target the repo owner
# instead — the operator who actually runs the panels + the agent. Override
# with SOVEREIGN_OS_OPERATOR_USER=<name>.
if [ "${OPERATOR}" = "root" ] && [ -z "${SOVEREIGN_OS_OPERATOR_USER:-}" ]; then
  __repo_owner="$(stat -c '%U' "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)" 2>/dev/null || true)"
  [ -n "${__repo_owner}" ] && [ "${__repo_owner}" != "root" ] && OPERATOR="${__repo_owner}"
fi
# visudo lives in /usr/sbin — often absent from a login PATH.
VISUDO="$(command -v visudo 2>/dev/null || true)"; [ -n "${VISUDO}" ] || VISUDO="/usr/sbin/visudo"

# ── the allow-list: command name → resolved full path (absent tools skipped) ──
# diagnostics (read-only): the hardware/system probes the panels + doctor want
DIAG=(dmidecode lshw lspci lsusb lsblk nvme smartctl sensors nvidia-smi zpool zfs journalctl)
# image inspection: loop-mount a built .raw to verify it (shadow / os-release /
# boot chain) BEFORE flashing. HIGH-RISK primitives — enabled because image
# verification is the whole point; drop them if you'd rather verify only in QEMU.
IMAGE=(losetup mount umount)

resolve() {  # print full path if the command exists (incl. sbin), else nothing
  local c="$1" p d
  if p="$(command -v "$c" 2>/dev/null)" && [ -n "$p" ]; then echo "$p"; return; fi
  # sudo-relevant tools (losetup/dmidecode/nvme/smartctl/sensors) live in sbin,
  # which is often absent from a login PATH — search it explicitly.
  for d in /usr/bin /bin /usr/sbin /sbin; do
    [ -x "$d/$c" ] && { echo "$d/$c"; return 0; }
  done
  return 0   # not found → empty output, still success (caller skips empties)
}

build_body() {
  echo "# sovereign-os operator NOPASSWD allow-list"
  echo "# generated by scripts/operator/operator-sudoers.sh — DO NOT hand-edit"
  echo "# (re-run the script to regenerate; edit the script's allow-list instead)"
  echo "# operator: ${OPERATOR}"
  local paths=()
  local c p
  for c in "${DIAG[@]}" "${IMAGE[@]}"; do
    p="$(resolve "$c")"
    [ -n "$p" ] && paths+=("$p")
  done
  if [ "${#paths[@]}" -eq 0 ]; then
    echo "# (no allow-listed commands found on PATH)" >&2
    return 1
  fi
  # one Cmnd_Alias keeps the spec readable + auditable
  local joined
  joined="$(printf '%s, ' "${paths[@]}")"; joined="${joined%, }"
  echo "Cmnd_Alias SOVEREIGN_OS_OPS = ${joined}"
  echo "${OPERATOR} ALL=(root) NOPASSWD: SOVEREIGN_OS_OPS"
}

cmd_print() { build_body; }

cmd_check() {
  if [ -f "${DEST}" ]; then
    echo "installed: ${DEST}"
    echo "  operator: $(grep -oE '^[a-zA-Z0-9_-]+ ALL=' "${DEST}" 2>/dev/null | awk '{print $1}' | head -1)"
    echo "  commands: $(grep -c ',' "${DEST}" 2>/dev/null || echo '?') allow-listed"
    sudo -n -l >/dev/null 2>&1 && echo "  ✓ NOPASSWD active for the current user" || echo "  (run as the operator to test NOPASSWD)"
  else
    echo "not installed (${DEST} absent) — run: sudo $0"
  fi
}

cmd_install() {
  [ "$(id -u)" -eq 0 ] || { echo "install needs root: sudo $0" >&2; exit 2; }
  local tmp; tmp="$(mktemp)"
  build_body > "${tmp}"
  # validate BEFORE placing it — a broken sudoers drop-in can lock out sudo
  if ! "${VISUDO}" -cf "${tmp}" >/dev/null 2>&1; then
    echo "✗ generated sudoers failed visudo validation — not installing:" >&2
    "${VISUDO}" -cf "${tmp}" >&2 || true
    rm -f "${tmp}"; exit 1
  fi
  if [ -f "${DEST}" ] && cmp -s "${tmp}" "${DEST}"; then
    echo "✓ already current: ${DEST}"; rm -f "${tmp}"; return 0
  fi
  install -m 0440 -o root -g root "${tmp}" "${DEST}"
  rm -f "${tmp}"
  # final belt-and-suspenders: validate the whole sudoers tree
  "${VISUDO}" -c >/dev/null 2>&1 && echo "✓ installed + validated: ${DEST} (operator=${OPERATOR})" \
    || { echo "✗ sudoers tree invalid after install — removing" >&2; rm -f "${DEST}"; exit 1; }
}

cmd_uninstall() {
  [ "$(id -u)" -eq 0 ] || { echo "uninstall needs root: sudo $0 --uninstall" >&2; exit 2; }
  rm -f "${DEST}" && echo "✓ removed ${DEST}"
}

case "${1:-install}" in
  --print|print)         cmd_print ;;
  --check|check)         cmd_check ;;
  --uninstall|uninstall) cmd_uninstall ;;
  ""|--install|install)  cmd_install ;;
  -h|--help)             grep '^#' "$0" | sed 's/^# \{0,1\}//' ;;
  *) echo "usage: $0 [--print|--install|--uninstall|--check]" >&2; exit 2 ;;
esac
